import type { BlogPost } from "./blog";

// 15 evergreen articles. No dates rendered anywhere in the UI.
export const NEW_BLOG_POSTS: BlogPost[] = [
  {
    slug: "flexbox-vs-grid-when-to-use-which",
    title: "Flexbox vs Grid: When to Use Which",
    description:
      "A practical comparison of Flexbox and Grid with real-world examples so you always pick the right tool without second-guessing.",
    readMinutes: 7,
    category: "Layout",
    tags: ["flexbox", "grid", "layout"],
    content: `Flexbox and Grid are not competitors. They solve different problems, and the shortest way to build reliable layouts is to know which one each pattern belongs to.\n\nA one-line rule that holds up in production: **Flexbox is for one-dimensional flows, Grid is for two-dimensional structure.**\n\n## When to reach for Flexbox\n\nUse Flexbox when items live on a single axis and you care about how they distribute, wrap or align along that axis.\n\n- Navigation bars where links sit in a row and push a CTA to the far right\n- Toolbars, tag rows, chip lists\n- A card footer with an avatar on the left and an action on the right\n- Any \`justify-content: space-between\` situation\n\n\`\`\`css\n.navbar {\n  display: flex;\n  align-items: center;\n  gap: 1rem;\n}\n.navbar .spacer { margin-left: auto; }\n\`\`\`\n\n## When to reach for Grid\n\nUse Grid when rows and columns matter together, when items need to align across both axes, or when you want an explicit layout skeleton.\n\n- Page shells with a header, sidebar, main and footer\n- Product grids that must stay perfectly aligned as items wrap\n- Complex form layouts where labels and inputs align across rows\n- Any layout you would draw as a rectangle sliced into cells\n\n\`\`\`css\n.shell {\n  display: grid;\n  grid-template-columns: 240px 1fr;\n  grid-template-rows: auto 1fr auto;\n  grid-template-areas:\n    "sidebar header"\n    "sidebar main"\n    "sidebar footer";\n  min-height: 100dvh;\n}\n\`\`\`\n\n## The trap: nesting them\n\nGrid and Flexbox nest happily. A Grid page shell often contains Flexbox toolbars inside each cell. That is normal and correct — do not force one primitive to do the whole job.\n\n## A decision checklist\n\n- Are items flowing on a single line or column? → **Flexbox**\n- Do items need to align across rows *and* columns? → **Grid**\n- Do you want to say "put this in the second column, third row"? → **Grid**\n- Do you want "push this element to the end of the row"? → **Flexbox**\n- Are you fighting one of them to do the other's job? → switch.\n\n## Real-world combos\n\nA dashboard is usually Grid on the outside and Flexbox on the inside. A pricing table is Grid across plans but Flexbox inside each plan card. A blog post is a single column (no layout primitive needed) with the header being a Flexbox row.\n\nThere is no prize for using fewer tools. There is a big prize for stopping the fight with CSS.`,
  },
  {
    slug: "understanding-css-specificity",
    title: "Understanding CSS Specificity: A Complete Guide",
    description:
      "A deep, example-driven walkthrough of how the cascade actually decides which rule wins, and how to stop needing !important.",
    readMinutes: 8,
    category: "Fundamentals",
    tags: ["specificity", "cascade"],
    content: `Specificity is the reason your button is green when you swore it was blue. It is not magic — it is a scoring system with clear rules.\n\n## The four-part score\n\nEvery selector produces a tuple \`(a, b, c, d)\`:\n\n- **a** — inline styles (\`style="..."\`)\n- **b** — number of IDs\n- **c** — number of classes, attribute selectors, pseudo-classes\n- **d** — number of elements and pseudo-elements\n\nHigher tuple wins, compared left to right. \`(0,1,0,0)\` beats \`(0,0,10,0)\` — one ID outranks any number of classes.\n\n## Worked examples\n\n\`\`\`css\n/* (0,0,1,1) */\na.button { color: blue; }\n\n/* (0,0,2,1) */\na.button.primary { color: green; }\n\n/* (0,1,0,1) */\na#cta { color: red; }\n\`\`\`\n\nThree rules target the same link. The ID selector wins, so the link is red — regardless of source order.\n\n## Source order only matters at a tie\n\nWhen two selectors have the exact same specificity, the later rule in the stylesheet wins. This is why plugin CSS loaded before your app CSS behaves; move it after and it starts overriding you.\n\n## \`:where()\` is the zero-specificity trick\n\n\`:where()\` matches like \`:is()\` but contributes **zero** to specificity. Wrap defaults in it and any real rule beats them.\n\n\`\`\`css\n:where(a) { color: inherit; }         /* (0,0,0,0) */\n.link-brand { color: var(--brand); }  /* (0,0,1,0) wins effortlessly */\n\`\`\`\n\n## Cascade layers change the game\n\n\`@layer\` lets you group rules; later layers beat earlier layers *regardless of specificity*. A single-class rule in a later layer overrides an ID in an earlier one.\n\n\`\`\`css\n@layer reset, base, components, utilities;\n\n@layer components { .btn { color: white; } }\n@layer utilities  { .text-black { color: black; } }\n\`\`\`\n\n## When you feel the urge to use !important\n\nStop. The urge is almost always a specificity mismatch. Try, in order:\n\n1. Lower the specificity of the rule you are fighting (use \`:where()\`).\n2. Move your override into a later cascade layer.\n3. Add one more class to your selector to nudge it over the top.\n4. Only after those three fail, reach for \`!important\` — and comment why.\n\nSpecificity feels arcane until you write out the tuples. After that, it is boringly predictable, which is exactly what CSS should be.`,
  },
  {
    slug: "10-css-tricks-every-developer-should-know",
    title: "10 CSS Tricks Every Developer Should Know",
    description:
      "Ten small, modern CSS features — clamp, aspect-ratio, gap, :is, accent-color and more — that quietly delete dozens of lines from your codebase.",
    readMinutes: 9,
    category: "Fundamentals",
    tags: ["tips", "modern-css"],
    content: `These are not obscure hacks. They are shipping features in every evergreen browser that most codebases still work around with JavaScript or extra markup.\n\n## 1. \`clamp()\` for fluid type\n\n\`\`\`css\nh1 { font-size: clamp(1.75rem, 2vw + 1rem, 3rem); }\n\`\`\`\n\nOne line replaces three media queries. It scales between a floor and a ceiling.\n\n## 2. \`aspect-ratio\` for boxes that stay proportional\n\n\`\`\`css\n.thumb { aspect-ratio: 16 / 9; width: 100%; }\n\`\`\`\n\nNo padding-bottom hack, no wrapper div.\n\n## 3. \`gap\` on Flexbox\n\nGap used to be Grid-only. It works on Flexbox now, which kills the "negative margin on the parent" pattern forever.\n\n## 4. \`:is()\` and \`:where()\`\n\n\`\`\`css\n:is(article, section) :is(h1, h2, h3) { line-height: 1.2; }\n\`\`\`\n\nOne rule instead of nine.\n\n## 5. \`accent-color\`\n\n\`\`\`css\ninput[type="checkbox"], input[type="radio"], progress { accent-color: var(--brand); }\n\`\`\`\n\nBrand your form controls without rebuilding them from scratch.\n\n## 6. \`scroll-margin-top\` for sticky headers\n\nIf you have a fixed header and anchor links, add \`scroll-margin-top\` to your headings so \`#section\` links do not land under the header.\n\n## 7. \`inset\` shorthand\n\n\`\`\`css\n.overlay { position: absolute; inset: 0; }\n\`\`\`\n\nReplaces four \`top/right/bottom/left: 0\` declarations.\n\n## 8. Logical properties\n\n\`margin-inline\`, \`padding-block\`, \`border-inline-end\` — write once, work in every writing direction, including RTL languages.\n\n## 9. \`content-visibility: auto\`\n\nSkip rendering off-screen sections until they scroll near the viewport. On long pages the paint cost drops dramatically.\n\n## 10. \`color-mix()\`\n\n\`\`\`css\n.btn:hover { background: color-mix(in oklch, var(--brand) 85%, black); }\n\`\`\`\n\nDerive hover, active and disabled states from one brand color without a Sass build step.\n\n## Pick two and start today\n\nYou do not need all ten in one PR. Pick \`clamp()\` for a fluid heading and \`aspect-ratio\` for one image. That's a real improvement you will notice tomorrow.`,
  },
  {
    slug: "css-custom-properties-practical-guide",
    title: "A Practical Guide to CSS Custom Properties (Variables)",
    description:
      "Go beyond `--brand: blue`. Real patterns for theming, component APIs and derived values with CSS custom properties.",
    readMinutes: 8,
    category: "Fundamentals",
    tags: ["variables", "theming"],
    content: `Everyone knows \`--color-primary: #3b82f6\`. Fewer people know that CSS custom properties are a full runtime API — they can be scoped, animated, computed from other properties, and used to give your components a real, ergonomic surface.\n\n## They are inherited\n\nUnlike Sass variables, CSS custom properties cascade. Set \`--radius: 12px\` on \`:root\` and every child sees it. Override it on a component and only that subtree changes.\n\n\`\`\`css\n:root { --radius: 12px; }\n.card--tight { --radius: 4px; }  /* only this card and its descendants */\n\`\`\`\n\n## Use them as component APIs\n\nInstead of a dozen modifier classes, expose a few well-named variables:\n\n\`\`\`css\n.button {\n  background: var(--button-bg, var(--brand));\n  color: var(--button-fg, white);\n  padding: var(--button-pad, .625rem 1rem);\n  border-radius: var(--radius, 8px);\n}\n\`\`\`\n\nConsumers now theme the button by setting variables, not by writing new selectors.\n\n## Derive, do not duplicate\n\nUse \`color-mix()\` and \`calc()\` to compute related values from one source:\n\n\`\`\`css\n:root {\n  --brand: #6b5bff;\n  --brand-hover: color-mix(in oklch, var(--brand) 85%, black);\n  --brand-tint:  color-mix(in oklch, var(--brand) 15%, white);\n}\n\`\`\`\n\nChange \`--brand\` and hover/tint follow automatically.\n\n## Toggle themes with a single attribute\n\n\`\`\`css\n:root                     { --bg: #fff; --fg: #111; }\n[data-theme="dark"]       { --bg: #0b0d10; --fg: #f5f7fa; }\nbody { background: var(--bg); color: var(--fg); }\n\`\`\`\n\nOne attribute swap, whole theme changes. No JS-driven class ceremony.\n\n## Type them with @property\n\n\`\`\`css\n@property --angle {\n  syntax: '<angle>';\n  inherits: false;\n  initial-value: 0deg;\n}\n\`\`\`\n\nRegistered custom properties can be animated smoothly — try animating a gradient angle without \`@property\` and it will snap; with it, it will glide.\n\n## Read them from JavaScript\n\n\`\`\`js\nconst radius = getComputedStyle(el).getPropertyValue('--radius');\nel.style.setProperty('--radius', '20px');\n\`\`\`\n\nOne shared vocabulary between design tokens, CSS and JS.\n\nCustom properties are the closest CSS has to a real programming language surface. Use them like variables in code — few, well-named, and doing real work.`,
  },
  {
    slug: "responsive-layouts-without-media-queries",
    title: "Building Responsive Layouts Without Media Queries",
    description:
      "Container queries, intrinsic sizing and clamp() together can carry a whole design system. Here is when to reach for each.",
    readMinutes: 7,
    category: "Layout",
    tags: ["responsive", "container-queries", "clamp"],
    content: `Media queries answer the wrong question. They ask "how big is the viewport?" when what you actually want to know is "how big is *this component*?" and "does its content still fit?"\n\nThree modern tools let you skip most breakpoints.\n\n## 1. \`clamp()\` for fluid sizing\n\n\`\`\`css\n.section { padding-inline: clamp(1rem, 4vw, 4rem); }\nh1 { font-size: clamp(1.5rem, 2vw + 1rem, 3rem); }\n\`\`\`\n\nType and spacing scale smoothly between a floor and ceiling. No breakpoints, no jumps.\n\n## 2. Intrinsic sizing with \`minmax()\` and \`auto-fit\`\n\n\`\`\`css\n.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(min(240px, 100%), 1fr));\n  gap: 1rem;\n}\n\`\`\`\n\nOne line, and the grid becomes 1/2/3/4 columns as space allows. The \`min(240px, 100%)\` prevents overflow on narrow screens — a common gotcha.\n\n## 3. Container queries for real component responsiveness\n\n\`\`\`css\n.card { container-type: inline-size; }\n\n@container (min-width: 420px) {\n  .card__body { display: grid; grid-template-columns: 120px 1fr; gap: 1rem; }\n}\n\`\`\`\n\nThe same card sits in a wide grid *and* in a narrow sidebar and lays itself out correctly in both. No JavaScript, no wrapper detection.\n\n## When you still want a media query\n\nMedia queries are still right for **page-level** decisions: showing or hiding a whole sidebar, switching between mobile and desktop navigation shells. That is genuinely a viewport question.\n\n## A layered strategy\n\n- Page shell → media query (once).\n- Section spacing and type → \`clamp()\`.\n- Card grids → \`auto-fit\` + \`minmax\`.\n- Individual components that live in different slots → container queries.\n\nStart from that layering and you'll write about 10% of the breakpoints you used to.`,
  },
  {
    slug: "css-animations-and-transitions-guide",
    title: "The Complete Guide to CSS Animations and Transitions",
    description:
      "How to build smooth, GPU-friendly motion in CSS — and how to avoid the properties that cause jank.",
    readMinutes: 9,
    category: "Performance",
    tags: ["animation", "transitions", "performance"],
    content: `A great UI feels responsive because motion is doing the emotional work — telling the user what changed, what came from where, what is loading. Bad motion feels stuck. The difference is almost always which properties you animate.\n\n## Transitions vs animations\n\n- **Transitions** interpolate between two states triggered by a change (hover, class add, attribute swap).\n- **Animations** run a defined keyframe sequence, optionally on load, on loop, or on demand.\n\nUse transitions for state changes; use animations for anything that has more than two frames or must run without user input.\n\n## The performance rule of thumb\n\nAnimate only \`transform\` and \`opacity\`. These are composited on the GPU and do not trigger layout or paint on the main thread.\n\n\`\`\`css\n/* smooth */\n.card { transition: transform .2s ease, opacity .2s ease; }\n.card:hover { transform: translateY(-2px); }\n\n/* janky — triggers layout every frame */\n.card { transition: top .2s ease, height .2s ease; }\n\`\`\`\n\nSame visual idea, wildly different frame budget.\n\n## Duration and easing\n\n- Micro-interactions (hover, focus): **120–200ms**\n- Enter/exit transitions: **200–320ms**\n- Larger motion (page transitions, hero animations): **320–500ms**\n\nDefault easing (\`ease\`) is fine for exits. For entrances that should feel snappy, use a custom bezier with a fast start and slow end: \`cubic-bezier(.2, .8, .2, 1)\`.\n\n## Keyframes for repeated motion\n\n\`\`\`css\n@keyframes pulse {\n  from { transform: scale(1);   opacity: 1; }\n  to   { transform: scale(1.3); opacity: 0; }\n}\n\n.ping { animation: pulse 1.4s ease-out infinite; }\n\`\`\`\n\n## Respect \`prefers-reduced-motion\`\n\nThis is not optional. Enough users have vestibular disorders that any animated site needs this fallback:\n\n\`\`\`css\n@media (prefers-reduced-motion: reduce) {\n  *, *::before, *::after {\n    animation-duration: .001ms !important;\n    transition-duration: .001ms !important;\n  }\n}\n\`\`\`\n\n## The \`@starting-style\` trick\n\nFor entrances on newly-added elements you can now transition *from* an initial state that only applies on first render:\n\n\`\`\`css\n.toast { opacity: 1; transition: opacity .2s; }\n@starting-style { .toast { opacity: 0; } }\n\`\`\`\n\nNo JavaScript, no double-render dance.\n\nMotion is polish, but polish is the thing users remember. Get \`transform\` and \`opacity\` right and everything else is a bonus.`,
  },
  {
    slug: "neumorphism-glassmorphism-and-beyond",
    title: "Neumorphism, Glassmorphism, and Beyond: A Guide to Modern UI Trends",
    description:
      "A quick tour through the visual styles shaping product UI — with the CSS recipes and the trade-offs of each.",
    readMinutes: 7,
    category: "Design Trends",
    tags: ["trends", "styles", "ui"],
    content: `Every couple of years a new visual style catches on and product teams start reaching for it. Here is a working developer's guide to the ones that actually shipped, with the CSS recipe and the reason each one caught on.\n\n## Neumorphism\n\nSoft plastic. Elements look like they are pressed out of the same material as the background, using two shadows: one dark on the bottom-right, one light on the top-left.\n\n\`\`\`css\n.neu {\n  background: #e0e5ec;\n  border-radius: 16px;\n  box-shadow: 8px 8px 16px #b8bec6, -8px -8px 16px #ffffff;\n}\n\`\`\`\n\n**Watch out:** contrast is famously bad, which is why almost no accessibility-audited product ships pure neumorphism. Use it on decorative surfaces, not interactive controls, unless you can prove the contrast.\n\n## Glassmorphism\n\nFrosted glass over a colorful background: translucent layer, blurred backdrop, thin border, subtle shadow.\n\n\`\`\`css\n.glass {\n  background: rgba(255, 255, 255, .08);\n  border: 1px solid rgba(255, 255, 255, .18);\n  backdrop-filter: blur(16px) saturate(140%);\n  border-radius: 16px;\n}\n\`\`\`\n\n**Watch out:** \`backdrop-filter\` is a real GPU cost. Do not layer five glass panels on a phone.\n\n## Claymorphism\n\nInflated 3D shapes with soft inner and outer shadows. Reads as friendly, physical, kid-friendly.\n\n\`\`\`css\n.clay {\n  background: #6b5bff;\n  border-radius: 32px;\n  box-shadow:\n    0 20px 40px rgba(107,91,255,.35),\n    inset 0 -8px 0 rgba(0,0,0,.15),\n    inset 0 8px 0 rgba(255,255,255,.25);\n}\n\`\`\`\n\n## Neubrutalism\n\nRaw, chunky, unapologetic. Flat colors, thick black borders, hard offset shadows.\n\n\`\`\`css\n.brut {\n  background: #ffd23f;\n  border: 3px solid #000;\n  box-shadow: 6px 6px 0 #000;\n  border-radius: 0;\n}\n\`\`\`\n\n## Which one for your product?\n\n- Enterprise / SaaS → clean flat with layered shadows (see our shadow-layering post).\n- Consumer / playful → claymorphism or neubrutalism, in moderation.\n- Media / creative → glassmorphism over vivid photography.\n- Fintech / trust-heavy → conservative flat, avoid trend styles.\n\nTrends are tools, not identities. Pick the one that says the right thing about your product and skip the rest.`,
  },
  {
    slug: "tailwind-bootstrap-plain-css-coexist",
    title: "Why Tailwind, Bootstrap, and Plain CSS Can Coexist",
    description:
      "An honest comparison of the three most common styling approaches and when each one actually earns its place.",
    readMinutes: 8,
    category: "Fundamentals",
    tags: ["tailwind", "bootstrap", "architecture"],
    content: `The framework wars are boring. In real teams, the honest answer is usually "we use two of them, sometimes all three, and it's fine."\n\nHere is a straight comparison, no dogma.\n\n## Plain CSS (with modern features)\n\n**Best when:** you are building a design system, a landing page, or anything with a strong custom visual identity. Custom properties, cascade layers and \`color-mix()\` cover most of what people used to reach for Sass for.\n\n**Weakness:** you have to invent naming and structure. Without a convention (BEM, ITCSS, cube), files drift.\n\n## Bootstrap\n\n**Best when:** you need a working, opinionated UI *this week*. Admin dashboards, internal tools, MVPs where visual differentiation is not the point. It brings a grid, components, forms, and utilities in one download.\n\n**Weakness:** everything looks a bit like Bootstrap unless you invest in theming. Bundle size includes components you never use.\n\n## Tailwind\n\n**Best when:** you want speed *and* full design control. It gives you a curated vocabulary of utility classes tied to design tokens. Once the team learns the vocabulary, iteration is very fast.\n\n**Weakness:** class strings can get long. The mental jump is real — new hires need a week. Requires a build step.\n\n## They actually mix well\n\n- Use **Bootstrap** for a legacy admin section that no one wants to redesign.\n- Use **Tailwind** for the new marketing site and product UI.\n- Use **plain CSS** in your design-system layer, exposing tokens (\`--brand\`, \`--radius\`, \`--space-4\`) that Tailwind config and Bootstrap variables both consume.\n\nThat way each layer plays to its strengths. Tailwind is not going to redesign your legacy admin, and plain CSS is not going to help a two-person team ship a dashboard by Friday.\n\n## A useful test\n\nAsk: *"if I threw away this styling approach tomorrow, would the app still work?"* Design systems built on custom properties survive. Utility class strings and component libraries are more replaceable than we like to admit, and that's fine — replaceable is good.\n\n## The one thing that always wins\n\nWhichever approach you pick, put shared decisions in tokens. Color, spacing, radius, shadow. Everything else is negotiable.`,
  },
  {
    slug: "common-css-mistakes-and-how-to-avoid-them",
    title: "Common CSS Mistakes and How to Avoid Them",
    description:
      "A practical debugging checklist for the bugs that eat everyone's afternoon: collapsing margins, unexpected specificity, stacking contexts and more.",
    readMinutes: 8,
    category: "Fundamentals",
    tags: ["debugging", "bugs"],
    content: `Every CSS bug feels unique, but most of them collapse into the same five root causes. Learn to recognize them and your average debugging time drops a lot.\n\n## 1. Margin collapse\n\nVertical margins between adjacent block boxes collapse into one. If you set \`margin-top: 24px\` on a heading and \`margin-bottom: 24px\` on the paragraph above, you get 24px total — not 48.\n\nFixes: add \`display: flow-root\` or \`padding\` to the parent, or switch to a Flexbox/Grid container (which do not collapse margins).\n\n## 2. Percentage heights on non-sized parents\n\n\`height: 100%\` needs a parent with a defined height. On a plain \`<div>\`, the browser has nothing to compute the percentage against, and you get 0.\n\nUse \`min-height: 100dvh\` on the root shell, or Flex/Grid children which stretch by default.\n\n## 3. Unexpected stacking contexts\n\nAdding \`transform\`, \`filter\`, \`opacity < 1\`, or \`will-change\` creates a new stacking context. Suddenly your \`z-index: 9999\` modal sits under a header, because both are in different contexts and the header's context is on top.\n\nWhen a \`z-index\` isn't behaving, look up the DOM tree for anything that creates a stacking context and rearrange those, not the \`z-index\` value.\n\n## 4. Fighting specificity with !important\n\nCovered in depth in our specificity guide. Short version: \`!important\` is a smell. Ninety percent of the time you can fix the issue by lowering the losing selector's specificity with \`:where()\` or moving your override into a later cascade layer.\n\n## 5. \`overflow: hidden\` clipping things you wanted visible\n\nHiding overflow on a container also hides dropdowns, tooltips and menus that rely on being positioned outside it. Use \`overflow: clip\` (which behaves like \`hidden\` for scrolling but plays nicer with popovers) or move the popover to a portal/dialog element.\n\n## Bonus: forgetting \`box-sizing: border-box\`\n\nModern resets set this by default, but if you inherit an old codebase, missing \`box-sizing\` will make every \`width: 100%\` element blow past its container the moment you add padding. Add this once at the top and never think about it again:\n\n\`\`\`css\n*, *::before, *::after { box-sizing: border-box; }\n\`\`\`\n\n## A debugging routine that works\n\n1. Add \`outline: 2px solid red\` to the element that's misbehaving.\n2. Inspect its computed styles, not the source styles — the source lies about what won.\n3. Look at the parent chain for stacking contexts, overflow clips, and layout modes.\n4. Try to reproduce in a minimal HTML file. Half the time the fix reveals itself when you strip the noise.`,
  },
  {
    slug: "beginners-guide-to-css-grid",
    title: "A Beginner's Guide to CSS Grid: From Zero to Confident",
    description:
      "A structured tutorial that takes you from your first grid to real page layouts, one small step at a time.",
    readMinutes: 10,
    category: "Tutorials",
    tags: ["grid", "layout", "tutorial"],
    content: `Grid is often taught as a wall of properties. This tutorial is the opposite: one small idea per step, building up to a real layout at the end.\n\n## Step 1: what grid actually is\n\nA grid container has rows and columns. You put items into cells. That is the whole model.\n\n\`\`\`css\n.container { display: grid; }\n\`\`\`\n\nAdd nothing else and you get one column with as many rows as items.\n\n## Step 2: define columns\n\n\`\`\`css\n.container { display: grid; grid-template-columns: 1fr 1fr 1fr; }\n\`\`\`\n\n\`fr\` means "fraction of the free space." Three \`1fr\` columns share the row equally.\n\n## Step 3: gaps\n\n\`\`\`css\n.container { gap: 1rem; }\n\`\`\`\n\nOne line, spacing between every row and column. No margin math.\n\n## Step 4: repeat and minmax\n\n\`\`\`css\ngrid-template-columns: repeat(3, 1fr);\n\`\`\`\n\nAnd for responsive grids that "just work":\n\n\`\`\`css\ngrid-template-columns: repeat(auto-fit, minmax(240px, 1fr));\n\`\`\`\n\nAs the container grows, columns are added; as it shrinks, they wrap.\n\n## Step 5: placing items explicitly\n\n\`\`\`css\n.hero { grid-column: 1 / -1; }        /* full width */\n.sidebar { grid-row: span 2; }        /* two rows tall */\n\`\`\`\n\nNumbers refer to grid *lines*, not cells. \`-1\` means the last line.\n\n## Step 6: named areas — the readable way to lay out a page\n\n\`\`\`css\n.shell {\n  display: grid;\n  grid-template-columns: 240px 1fr;\n  grid-template-rows: auto 1fr auto;\n  grid-template-areas:\n    "sidebar header"\n    "sidebar main"\n    "sidebar footer";\n}\n.sidebar { grid-area: sidebar; }\n.header  { grid-area: header; }\n.main    { grid-area: main; }\n.footer  { grid-area: footer; }\n\`\`\`\n\nYou can read the layout out loud. That is the point.\n\n## Step 7: alignment\n\nGrid has two axes and two alignment properties on each:\n\n- \`justify-items\` / \`justify-self\` — horizontal (inline axis)\n- \`align-items\` / \`align-self\` — vertical (block axis)\n\nPlus \`place-items: center\` as the classic "center a div" one-liner.\n\n## Step 8: build the final layout\n\nCombine everything: a responsive gallery inside a page shell with a sticky sidebar.\n\n\`\`\`css\n.shell {\n  display: grid;\n  grid-template-columns: 240px 1fr;\n  min-height: 100dvh;\n}\n.gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n  gap: 1rem;\n}\n\`\`\`\n\nYou now know enough Grid for 90% of real work. Reach for [DevTools' grid overlay](https://developer.chrome.com/docs/devtools/css/grid/) when you get stuck — it draws the lines and areas for you.`,
  },
  {
    slug: "optimizing-css-for-performance",
    title: "Optimizing CSS for Performance: What Actually Matters",
    description:
      "A practical guide to CSS performance: which properties are cheap, which are expensive, and how to keep animations at 60fps.",
    readMinutes: 8,
    category: "Performance",
    tags: ["performance", "optimization"],
    content: `Most "CSS performance" advice is about shrinking file size. That matters, but it is not usually the bottleneck. The real bottleneck is *runtime cost*: how much work the browser does when it repaints, relayouts, or animates your styles.\n\n## The three phases\n\n1. **Layout** — figuring out where every box goes.\n2. **Paint** — filling in the pixels.\n3. **Composite** — assembling GPU layers into the final frame.\n\nChanging a property that triggers layout is the most expensive. Composite is close to free.\n\n## Cheap vs expensive properties\n\n- **Composite-only (cheap):** \`transform\`, \`opacity\`, \`filter\` on a promoted layer.\n- **Paint (medium):** \`color\`, \`background-color\`, \`box-shadow\`, \`border-radius\`.\n- **Layout (expensive):** \`width\`, \`height\`, \`top\`, \`left\`, \`padding\`, \`margin\`, \`font-size\`.\n\nRule of thumb: animate \`transform\` and \`opacity\`. Toggle everything else on discrete states, not per frame.\n\n## Reduce selector work — but only if you have measured it\n\nModern engines are extremely good at selector matching. \`#foo\` is only marginally faster than \`.foo\`. Do not micro-optimize selectors unless a profile is telling you to; readable CSS wins.\n\n## \`content-visibility: auto\`\n\nFor long pages with many independent sections (blogs, docs, product listings), this one property lets the browser skip rendering off-screen sections until they scroll close to the viewport.\n\n\`\`\`css\n.article-section { content-visibility: auto; contain-intrinsic-size: 800px; }\n\`\`\`\n\n\`contain-intrinsic-size\` gives the browser a size guess so the scrollbar doesn't jump.\n\n## Reduce reflows in JavaScript\n\nBatch DOM reads and writes. Reading \`offsetHeight\` after writing to \`style.height\` forces a synchronous layout — do all reads first, then all writes.\n\n## Ship less CSS\n\n- Purge unused rules at build time (Tailwind does this automatically).\n- Split rarely-used styles into separate stylesheets with \`media\` attributes.\n- Inline the critical CSS for above-the-fold content; defer the rest.\n\n## Measure with the right tool\n\nDevTools → Performance → Render tab. Turn on **Paint flashing** to see what repaints when you interact. Turn on **Layer borders** to see what is on the GPU. That's how you find real bottlenecks, not by guessing which selector is slow.\n\nPerformance is not a checklist you finish. It is a habit of animating the cheap things and profiling before optimizing the expensive ones.`,
  },
  {
    slug: "the-box-model-explained",
    title: "The Box Model Explained (Finally, for Real)",
    description:
      "A clear conceptual walkthrough of content, padding, border and margin — and why box-sizing changes everything.",
    readMinutes: 6,
    category: "Fundamentals",
    tags: ["box-model", "beginners"],
    content: `Every element on a web page is a rectangular box. That box has four zones, and once you can picture them, every layout bug gets simpler.\n\n## The four zones, from inside out\n\n1. **Content** — the actual text, image, or child elements.\n2. **Padding** — space between the content and the border. Inherits the background.\n3. **Border** — the line around the padding.\n4. **Margin** — space between this box and its neighbors. Transparent; does not inherit the background.\n\nPicture a photo in a matted frame on a wall: the photo is content, the mat is padding, the frame is border, the space between this frame and the next painting on the wall is margin.\n\n## The width surprise\n\nBy default, \`width\` measures the **content** box. If you set \`width: 300px\` and then add \`padding: 20px\` and \`border: 2px\`, the box is actually \`300 + 40 + 4 = 344px\` wide. This has caused more layout bugs than any other single quirk of CSS.\n\n## The fix: box-sizing: border-box\n\n\`\`\`css\n*, *::before, *::after { box-sizing: border-box; }\n\`\`\`\n\nNow \`width\` includes padding and border. Set \`width: 300px\` and the box is 300px wide, period. Padding grows *inward*, eating into the content area.\n\nEvery modern project should have this line at the top of its reset. It's not optional; it's sanity.\n\n## Margin behaves oddly on purpose\n\nTwo things about margin that trip people up:\n\n- **Vertical margins collapse.** Adjacent block-level margins merge into the larger of the two. Flex and Grid children do not collapse.\n- **Auto horizontal margins center block elements** if they have a set width.\n\n## Debugging boxes visually\n\nDrop this into your dev environment when things look off:\n\n\`\`\`css\n* { outline: 1px solid rgba(255, 0, 0, .3); }\n\`\`\`\n\nOutline (unlike border) does not affect layout, so you see the box edges without moving anything.\n\nThat's the whole model. Once you can point at content/padding/border/margin on any element, you're done being surprised by CSS box math.`,
  },
  {
    slug: "accessible-css",
    title: "Accessible CSS: Writing Styles That Work for Everyone",
    description:
      "Practical, a11y-focused CSS: focus states, color contrast, reduced motion, and semantics that don't fight assistive tech.",
    readMinutes: 7,
    category: "Accessibility",
    tags: ["a11y", "accessibility"],
    content: `Accessible CSS is not a separate stylesheet you add later. It is a small set of habits that make every design work for keyboard users, screen readers, low-vision users and anyone with a vestibular disorder.\n\n## Never remove focus outlines without replacing them\n\nThe #1 accessibility crime in CSS:\n\n\`\`\`css\n:focus { outline: none; }  /* please do not */\n\`\`\`\n\nIf you dislike the default outline, replace it with something visible:\n\n\`\`\`css\n:focus-visible {\n  outline: 2px solid var(--brand);\n  outline-offset: 2px;\n  border-radius: 4px;\n}\n\`\`\`\n\n\`:focus-visible\` only shows the ring for keyboard users, so mouse-click focus rings don't clutter the design.\n\n## Respect \`prefers-reduced-motion\`\n\nA meaningful chunk of users have vestibular disorders. Motion should be either optional or off:\n\n\`\`\`css\n@media (prefers-reduced-motion: reduce) {\n  *, *::before, *::after {\n    animation-duration: .001ms !important;\n    transition-duration: .001ms !important;\n    scroll-behavior: auto !important;\n  }\n}\n\`\`\`\n\n## Hit color contrast targets\n\n- Body text: **4.5:1** minimum against the background.\n- Large text (18pt+ or 14pt bold): **3:1**.\n- Interactive components and graphical objects: **3:1**.\n\nUse our [contrast tool](/tools/contrast) — or your browser's DevTools — to check as you design, not after.\n\n## Do not convey information with color alone\n\nErrors are red *and* have an icon or label. Success is green *and* has a checkmark. Colorblind users must be able to tell states apart without seeing the hue.\n\n## Font sizes in \`rem\`, not \`px\`\n\nUsers who need larger text change their browser's default font size. \`px\` ignores that setting. \`rem\` respects it.\n\n\`\`\`css\nbody { font-size: 1rem; }\nh1   { font-size: 2rem; }\n\`\`\`\n\n## Do not hide content the wrong way\n\n- \`display: none\` and \`visibility: hidden\` also hide from screen readers.\n- \`opacity: 0\` still receives keyboard focus.\n- For visually hidden but assistive-tech-reachable content, use a proper \`.sr-only\` utility that clips the element off-screen.\n\n\`\`\`css\n.sr-only {\n  position: absolute;\n  width: 1px; height: 1px;\n  padding: 0; margin: -1px;\n  overflow: hidden; clip: rect(0, 0, 0, 0);\n  white-space: nowrap; border: 0;\n}\n\`\`\`\n\n## Test with the keyboard\n\nAt the end of every feature, tab through it. If you can't reach every interactive control, or you can't tell where focus is, the design fails accessibility — no audit needed.`,
  },
  {
    slug: "dark-mode-done-right",
    title: "Dark Mode Done Right: A CSS Implementation Guide",
    description:
      "Beyond a color flip — how to build a dark theme that respects user preferences, remembers choices, and doesn't wash out your brand.",
    readMinutes: 7,
    category: "Design Trends",
    tags: ["dark-mode", "theming"],
    content: `A good dark mode is not "invert everything." It is a second full design that shares tokens with the first. Here's how to build one that holds up.\n\n## Start with tokens, not colors\n\nExpose semantic tokens and set both themes against them:\n\n\`\`\`css\n:root {\n  --bg: #ffffff;\n  --surface: #f5f7fa;\n  --fg: #0b0d10;\n  --muted: #5b6472;\n  --brand: #6b5bff;\n}\n\n[data-theme="dark"] {\n  --bg: #0b0d10;\n  --surface: #14171c;\n  --fg: #f5f7fa;\n  --muted: #9aa3b2;\n  --brand: #8a7dff;   /* nudged lighter for dark backgrounds */\n}\n\nbody { background: var(--bg); color: var(--fg); }\n\`\`\`\n\nEvery component references tokens, never raw hex. Theme switching becomes free.\n\n## Follow the user by default\n\n\`\`\`css\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n    --bg: #0b0d10;\n    /* ...same dark values as above... */\n  }\n}\n\`\`\`\n\nUsers who haven't explicitly chosen a theme get the one their OS asked for.\n\n## Save the explicit choice\n\nWhen the user flips your toggle, write \`data-theme\` on \`<html>\` and persist to \`localStorage\`. On page load, read it before your styles apply to avoid a flash:\n\n\`\`\`html\n<script>\n  const saved = localStorage.getItem('theme');\n  if (saved) document.documentElement.dataset.theme = saved;\n</script>\n\`\`\`\n\nInline that in \`<head>\`, before your stylesheet.\n\n## Avoid pure black and pure white\n\nPure white on dark backgrounds strains the eyes; pure black under white text creates halation. Nudge them in: \`#f5f7fa\` on \`#0b0d10\` reads far better than \`#ffffff\` on \`#000000\`.\n\n## Rethink shadows and elevation\n\nShadows do less on dark backgrounds. To show elevation in dark mode, **lighten the surface** as it rises:\n\n\`\`\`css\n[data-theme="dark"] .card    { background: #14171c; }\n[data-theme="dark"] .card-hi { background: #1c2029; }  /* elevated */\n\`\`\`\n\nCombine with a subtle top-inner-shadow to hint at a highlight.\n\n## Tint your brand for dark\n\nThe same brand hex looks over-saturated on dark. Bump lightness slightly or mix with white:\n\n\`\`\`css\n[data-theme="dark"] { --brand: color-mix(in oklch, #6b5bff 80%, white); }\n\`\`\`\n\n## The one thing that surprises everyone\n\nImages. Photography looks fine in either theme; illustrations and screenshots with white backgrounds do not. Provide dark-mode variants for logos and illustrations, and prefer transparent PNG/SVG where possible.\n\nDark mode done well is invisible: users switch, and everything still feels intentional. That is the whole standard.`,
  },
  {
    slug: "from-figma-to-css",
    title: "From Figma to CSS: Translating Designs Into Code",
    description:
      "A practical workflow for turning Figma files into maintainable CSS — tokens, auto-layout, spacing scales, and the gotchas nobody warns you about.",
    readMinutes: 8,
    category: "Tutorials",
    tags: ["figma", "workflow", "design"],
    content: `The Figma-to-CSS handoff is where most design systems quietly fall apart. A handful of habits on both sides make it click.\n\n## Extract tokens first, components later\n\nBefore you touch a single component, read the Figma **Local Styles** and **Variables** and mirror them into CSS custom properties:\n\n\`\`\`css\n:root {\n  /* Color */\n  --brand-500: #6b5bff;\n  --brand-600: #574bd0;\n  --fg-body: #0b0d10;\n\n  /* Space (matches Figma's 4pt grid) */\n  --space-1: .25rem;   /* 4px */\n  --space-2: .5rem;\n  --space-3: .75rem;\n  --space-4: 1rem;\n\n  /* Radius */\n  --radius-sm: 4px;\n  --radius-md: 8px;\n  --radius-lg: 16px;\n\n  /* Type scale */\n  --text-sm: .875rem;\n  --text-base: 1rem;\n  --text-lg: 1.125rem;\n}\n\`\`\`\n\nOnce tokens exist, every component is a small translation problem instead of a from-scratch decision.\n\n## Auto-layout is Flexbox\n\nFigma's auto-layout maps almost 1:1 to Flexbox. Direction is \`flex-direction\`, spacing is \`gap\`, padding is \`padding\`, alignment controls are \`justify-content\` and \`align-items\`. Read the auto-layout panel and you have the CSS.\n\n## Constraints ≈ position + inset\n\n"Pin to right" is \`right: 0\`. "Center horizontally" is \`left: 50%; transform: translateX(-50%)\` or, on a Flex parent, \`margin-inline: auto\`. Nothing exotic.\n\n## The unit gotcha\n\nFigma works in pixels. Your web app should mostly work in \`rem\`. **Divide Figma pixel values by 16** to get \`rem\` — 16px = 1rem, 24px = 1.5rem, and so on. This one habit keeps text scaling for users who change their browser default.\n\n## Shadows: match the layer count, not just the values\n\nA Figma "Drop Shadow" is one shadow. If the designer stacked three shadows, your CSS \`box-shadow\` needs three comma-separated shadows. Do not average them into one — you will lose the depth. (See our layered-shadows post.)\n\n## Effects that don't translate\n\n- **Layer blur** → \`filter: blur()\` on the element.\n- **Background blur** → \`backdrop-filter: blur()\` — check browser support.\n- **Blend modes** → \`mix-blend-mode\` on the top layer.\n- **Gradient stops with mid-points** → CSS gradients don't support Figma's per-stop midpoint control; add an extra stop instead.\n\n## Line-height in Figma vs CSS\n\nFigma displays line-height in pixels; CSS accepts unitless values that scale with font size. When possible, translate \`24px on 16px font\` to \`line-height: 1.5\` — it will hold up when font size changes.\n\n## The handoff checklist\n\nWhen you receive a design, before writing CSS, confirm:\n\n- Are colors picked from published styles/variables, or hardcoded? (If hardcoded, ask.)\n- Is spacing on the 4pt grid?\n- Is every component built with auto-layout?\n- Are shadow and radius values consistent with the design system, or one-offs?\n\nThose four questions catch 80% of the "the design and the build don't match" tickets before they happen.`,
  },
];