export type QLevel = "Basic" | "Medium" | "Advanced";
export type QLang = "HTML" | "CSS";

export type InterviewQuestion = {
  id: string;
  lang: QLang;
  level: QLevel;
  topic: string;
  question: string;
  answer: string;
  code?: string;
};

// Helper to keep the file compact.
const q = (
  id: string,
  lang: QLang,
  level: QLevel,
  topic: string,
  question: string,
  answer: string,
  code?: string,
): InterviewQuestion => ({ id, lang, level, topic, question, answer, code });

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // ============ CSS BASIC ============
  q(
    "css-b-1",
    "CSS",
    "Basic",
    "Box Model",
    "What is the CSS box model?",
    "Every element is a rectangular box composed of four zones from the inside out: content, padding, border, and margin. The content holds text or child boxes, padding is the transparent space inside the border, the border wraps the padding, and margin is the outer space that separates the box from its siblings. By default, `width` and `height` size only the content box, so padding and border add to the visible size unless you switch to `border-box`.",
    "* { box-sizing: border-box; }\n.card { width: 320px; padding: 16px; border: 1px solid #ddd; }",
  ),
  q(
    "css-b-2",
    "CSS",
    "Basic",
    "Box Model",
    "What does `box-sizing: border-box` do?",
    "It changes how `width` and `height` are calculated. With the default `content-box`, padding and border are added on top of the width. With `border-box`, padding and border are included inside the declared width, so a `width: 200px` box is always 200px wide regardless of padding. Applying it globally makes layouts more predictable.",
    "*, *::before, *::after { box-sizing: border-box; }",
  ),
  q(
    "css-b-3",
    "CSS",
    "Basic",
    "Selectors",
    "What is the difference between class and ID selectors?",
    "A class selector (`.name`) targets any element with that class and can be reused across the page; an ID selector (`#name`) targets a single element and must be unique per document. IDs also have much higher specificity (100 vs 10), so overriding an ID rule with a class is often impossible without another ID or `!important`. Prefer classes for styling; reserve IDs for anchor targets and JS hooks.",
    ".button { color: white; }\n#header { position: sticky; top: 0; }",
  ),
  q(
    "css-b-4",
    "CSS",
    "Basic",
    "Specificity",
    "How is CSS specificity calculated?",
    "Specificity is a four-part score: inline styles, IDs, classes/attributes/pseudo-classes, and elements/pseudo-elements. Higher values win. `!important` overrides all of these except a later `!important` with equal or higher specificity. The universal selector `*` and combinators contribute nothing.",
    "/* 0,1,2,1 */ a#nav.link:hover span { }",
  ),
  q(
    "css-b-5",
    "CSS",
    "Basic",
    "Cascade",
    "What is the CSS cascade?",
    "The cascade is the algorithm the browser uses to resolve which declaration wins when multiple rules apply to the same element. It considers, in order: origin & importance (author vs user-agent vs `!important`), specificity, and finally source order. Later rules with equal specificity override earlier ones.",
    "/* Second rule wins by source order */\n.btn { color: blue; }\n.btn { color: red; }",
  ),
  q(
    "css-b-6",
    "CSS",
    "Basic",
    "Units",
    "What is the difference between `px`, `em`, and `rem`?",
    "`px` is an absolute CSS pixel — always the same size. `em` is relative to the font-size of the current element and compounds through nesting, which can cause runaway sizing. `rem` is relative to the root `<html>` font-size, giving predictable scaling. Use `rem` for typography and spacing; use `em` when a value should scale with its component's own text.",
    "html { font-size: 16px; }\nh1 { font-size: 2rem; } /* 32px */\n.card { padding: 1em; } /* relative to card's font-size */",
  ),
  q(
    "css-b-7",
    "CSS",
    "Basic",
    "Colors",
    "What are the common ways to define colors in CSS?",
    "You can use named keywords (`red`), hex (`#ff0000`, `#f00`), `rgb()` / `rgba()`, `hsl()` / `hsla()`, and modern `oklch()` / `lab()` / `color()` functions. HSL is intuitive for building palettes because hue, saturation and lightness map to how designers think. OKLCH gives perceptually uniform lightness across hues.",
    ".a { color: #3b82f6; }\n.b { color: rgb(59 130 246 / 0.8); }\n.c { color: hsl(217 91% 60%); }",
  ),
  q(
    "css-b-8",
    "CSS",
    "Basic",
    "Display",
    "What is the difference between `block`, `inline`, and `inline-block`?",
    "Block elements start on a new line and stretch to fill available width; `width`, `height`, and vertical margin/padding all apply. Inline elements flow with surrounding text, ignore `width`/`height`, and only respect horizontal padding/margin visually. Inline-block flows inline but accepts width, height, and full box-model properties — ideal for buttons in a row of text.",
    ".pill { display: inline-block; width: 80px; padding: 4px 12px; }",
  ),
  q(
    "css-b-9",
    "CSS",
    "Basic",
    "Positioning",
    "Explain `static`, `relative`, `absolute`, `fixed`, and `sticky` positioning.",
    "`static` is the default (element flows normally, `top/left` ignored). `relative` keeps the element in flow but lets you nudge it and creates a positioning context. `absolute` removes it from flow and positions it relative to the nearest positioned ancestor. `fixed` positions relative to the viewport (or a `transform`ed ancestor). `sticky` toggles between relative and fixed at a scroll threshold.",
    ".parent { position: relative; }\n.badge { position: absolute; top: 8px; right: 8px; }\n.header { position: sticky; top: 0; }",
  ),
  q(
    "css-b-10",
    "CSS",
    "Basic",
    "Flexbox",
    "What is Flexbox and when should you use it?",
    "Flexbox is a one-dimensional layout system: you arrange items along a single main axis (row or column) with an implicit cross axis. It excels at aligning components in a row, distributing space, centering content, and reordering items. Use Grid when you need two-dimensional control.",
    ".row { display: flex; gap: 12px; align-items: center; justify-content: space-between; }",
  ),
  q(
    "css-b-11",
    "CSS",
    "Basic",
    "Flexbox",
    "How do you center an element both horizontally and vertically with Flexbox?",
    "Turn the parent into a flex container and use `justify-content` for the main axis and `align-items` for the cross axis. This is the go-to modern centering technique — one parent rule and the child stays centered regardless of size.",
    ".center { display: flex; justify-content: center; align-items: center; min-height: 100vh; }",
  ),
  q(
    "css-b-12",
    "CSS",
    "Basic",
    "Grid",
    "What is CSS Grid?",
    "CSS Grid is a two-dimensional layout system: you define rows and columns on the container and place items into cells or spans. It's ideal for page-level layout, dashboards, image galleries, and any UI with a real grid structure. Flexbox handles a single axis; Grid handles both simultaneously.",
    ".grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }",
  ),
  q(
    "css-b-13",
    "CSS",
    "Basic",
    "Units",
    "What are viewport units?",
    "`vw` and `vh` equal 1% of viewport width/height. `vmin` and `vmax` take the smaller/larger of the two. Newer units — `svh`, `lvh`, `dvh` — respect mobile browser UI (address bars) so full-height layouts don't jump. Prefer `dvh` for full-screen sections on mobile.",
    ".hero { min-height: 100dvh; }",
  ),
  q(
    "css-b-14",
    "CSS",
    "Basic",
    "Media Queries",
    "What is a media query?",
    "A media query applies CSS conditionally based on device characteristics — most commonly viewport width. It's the foundation of responsive design: define a base mobile layout, then use `@media (min-width: …)` to progressively enhance for larger screens.",
    "@media (min-width: 768px) { .grid { grid-template-columns: repeat(3, 1fr); } }",
  ),
  q(
    "css-b-15",
    "CSS",
    "Basic",
    "Pseudo-classes",
    "What are pseudo-classes? Give examples.",
    "Pseudo-classes select elements based on state or position rather than markup. Common ones: `:hover`, `:focus`, `:active`, `:disabled`, `:checked`, `:first-child`, `:last-child`, `:nth-child()`, `:not()`, `:focus-visible`. They let you style dynamic UI states without JavaScript.",
    "button:hover { background: #333; }\nli:nth-child(odd) { background: #f5f5f5; }",
  ),
  q(
    "css-b-16",
    "CSS",
    "Basic",
    "Pseudo-elements",
    "What is the difference between `::before` and `::after`?",
    "Both are pseudo-elements that insert generated content into an element. `::before` renders as the first child, `::after` as the last child. They require a `content` property (even if empty) to render. They're commonly used for decorative shapes, icons, tooltips, and clearing floats.",
    ".quote::before { content: '“'; font-size: 2em; }\n.quote::after { content: '”'; }",
  ),
  q(
    "css-b-17",
    "CSS",
    "Basic",
    "Colors",
    "What is the difference between `visibility: hidden` and `display: none`?",
    "`display: none` removes the element from the layout entirely — no space is reserved and it's inaccessible to screen readers by default. `visibility: hidden` keeps the box in the layout (space is reserved) but paints nothing and blocks pointer events. Use `display: none` for toggled UI and `visibility: hidden` when you need to keep layout stable.",
    ".is-hidden { display: none; }\n.is-invisible { visibility: hidden; }",
  ),
  q(
    "css-b-18",
    "CSS",
    "Basic",
    "Typography",
    "How do you set a fallback font stack?",
    "List fonts in order of preference and end with a generic family so the browser always has a match. This handles cases where the primary web font fails to load or isn't installed. Match the metrics of the fallback to your web font to reduce layout shift.",
    "body { font-family: 'Inter', system-ui, -apple-system, sans-serif; }",
  ),
  q(
    "css-b-19",
    "CSS",
    "Basic",
    "Backgrounds",
    "How do you make a background image cover the full container?",
    "Use `background-size: cover` to scale the image so it fills the container while preserving aspect ratio (cropping if needed). Pair it with `background-position: center` so the interesting part stays visible. `background-repeat: no-repeat` prevents tiling.",
    ".hero { background: url('/hero.jpg') center/cover no-repeat; }",
  ),
  q(
    "css-b-20",
    "CSS",
    "Basic",
    "Transitions",
    "What is a CSS transition?",
    "A transition animates a property change over time when the property's value changes (usually on hover, focus, or class toggle). You specify which properties to animate, duration, timing function, and delay. Only animatable properties (like color, transform, opacity) will actually tween.",
    ".btn { transition: background 200ms ease, transform 200ms ease; }\n.btn:hover { transform: translateY(-2px); }",
  ),
  q(
    "css-b-21",
    "CSS",
    "Basic",
    "Selectors",
    "What does the universal selector `*` do?",
    "`*` matches every element in the document. It's most commonly used for resets (`* { margin: 0; }`) or applying box-sizing globally. It has zero specificity, so it's easy to override.",
    "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }",
  ),
  q(
    "css-b-22",
    "CSS",
    "Basic",
    "Selectors",
    "What are attribute selectors?",
    "Attribute selectors match elements by attribute presence or value: `[type=email]`, `[href^='https']` (starts with), `[href$='.pdf']` (ends with), `[class*='btn']` (contains). Handy for styling form inputs, external links, or icons without extra classes.",
    "input[type='email'] { border-color: teal; }\na[href^='https']::after { content: ' ↗'; }",
  ),
  q(
    "css-b-23",
    "CSS",
    "Basic",
    "Layout",
    "How do you make a `<div>` fill its parent's height?",
    "Set `height: 100%` on the child, but the parent (and every ancestor up to `<html>`) must also have an explicit height for percentage to resolve. Modern layouts usually solve this with Flexbox (`flex: 1`) or Grid, which don't require the ancestor chain to declare heights.",
    ".parent { display: flex; }\n.child { flex: 1; }",
  ),
  q(
    "css-b-24",
    "CSS",
    "Basic",
    "Typography",
    "How do you truncate text with an ellipsis?",
    "Use `overflow: hidden`, `white-space: nowrap`, and `text-overflow: ellipsis` for single-line truncation. For multi-line, use `-webkit-line-clamp` with `display: -webkit-box`.",
    ".truncate { overflow: hidden; white-space: nowrap; text-overflow: ellipsis; }\n.clamp-2 { display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }",
  ),
  q(
    "css-b-25",
    "CSS",
    "Basic",
    "Colors",
    "What is the difference between `rgba()` and `hsla()`?",
    "Both add an alpha channel. `rgba()` mixes red, green, and blue channels — hard to reason about visually. `hsla()` uses hue, saturation, and lightness, which maps to how designers think about color, making it easier to build palettes and hover states.",
    ".overlay { background: hsla(217, 91%, 60%, 0.15); }",
  ),
  q(
    "css-b-26",
    "CSS",
    "Basic",
    "Backgrounds",
    "How do you create a linear gradient?",
    "`linear-gradient()` accepts a direction (angle or `to <side>`) followed by color stops. You can use multiple stops and specify positions to control the transition.",
    ".hero { background: linear-gradient(135deg, #6366f1, #22d3ee); }",
  ),
  q(
    "css-b-27",
    "CSS",
    "Basic",
    "Layout",
    "How do you horizontally center a block element?",
    "Give it a fixed or max width and set `margin-inline: auto` (or `margin: 0 auto`). This works because auto horizontal margins on a block element distribute the leftover space equally.",
    ".container { max-width: 1120px; margin-inline: auto; padding-inline: 16px; }",
  ),
  q(
    "css-b-28",
    "CSS",
    "Basic",
    "Selectors",
    "What is the descendant combinator vs the child combinator?",
    "The descendant combinator (space) matches any descendant at any depth: `.card p` matches every `<p>` inside `.card`. The child combinator (`>`) only matches direct children: `.card > p` matches paragraphs that are immediate children of `.card`, not those nested deeper.",
    ".menu li { }        /* any li inside .menu */\n.menu > li { }      /* only direct li children */",
  ),
  q(
    "css-b-29",
    "CSS",
    "Basic",
    "Layout",
    "What is the `z-index` property?",
    "`z-index` controls the stacking order of positioned elements (those with `position` other than `static`, or flex/grid items with `z-index` set). Higher values stack on top. It only compares elements within the same stacking context.",
    ".modal { position: fixed; z-index: 1000; }",
  ),
  q(
    "css-b-30",
    "CSS",
    "Basic",
    "Layout",
    "What does `overflow: auto` do?",
    "It shows scrollbars only when the content actually overflows the container. `overflow: scroll` always shows scrollbars, `hidden` clips overflow silently, and `visible` (default) lets content spill out.",
    ".scroll-area { max-height: 300px; overflow-y: auto; }",
  ),

  // ============ CSS MEDIUM ============
  q(
    "css-m-1",
    "CSS",
    "Medium",
    "Flexbox",
    "Explain `flex: 1` — what three values does it expand to?",
    "`flex` is shorthand for `flex-grow`, `flex-shrink`, and `flex-basis`. `flex: 1` expands to `1 1 0%`: the item can grow to consume free space, can shrink if space is tight, and starts from a zero basis so items share space equally regardless of their intrinsic size. `flex: auto` uses the item's natural size as the basis instead.",
    ".row { display: flex; gap: 8px; }\n.row > * { flex: 1; }",
  ),
  q(
    "css-m-2",
    "CSS",
    "Medium",
    "Grid",
    "What does `1fr` mean in `grid-template-columns`?",
    "`fr` is a fractional unit that represents a share of the remaining space after fixed-size tracks and gaps are subtracted. `1fr 1fr` splits the leftover space evenly; `2fr 1fr` gives the first column twice the leftover as the second. It's more expressive than percentages because it accounts for gaps automatically.",
    ".layout { display: grid; grid-template-columns: 240px 1fr; gap: 24px; }",
  ),
  q(
    "css-m-3",
    "CSS",
    "Medium",
    "Grid",
    "How do `auto-fit` and `auto-fill` differ in `repeat()`?",
    "Both create as many tracks as fit at the given minimum. `auto-fill` reserves empty tracks even when there aren't enough items, so items stay at their min size. `auto-fit` collapses those empty tracks so existing items expand to fill the row — great for responsive card grids.",
    ".cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; }",
  ),
  q(
    "css-m-4",
    "CSS",
    "Medium",
    "Positioning",
    "Why doesn't `position: absolute` seem to anchor to my parent?",
    "`absolute` positions relative to the nearest ancestor whose `position` is not `static`. If no ancestor is positioned, it falls back to the initial containing block (viewport). The fix is to set `position: relative` on the intended parent.",
    ".card { position: relative; }\n.card .badge { position: absolute; top: 8px; right: 8px; }",
  ),
  q(
    "css-m-5",
    "CSS",
    "Medium",
    "Stacking",
    "What is a stacking context and how is it created?",
    "A stacking context is an isolated z-axis in which `z-index` values are compared. Once an element creates a stacking context, its descendants can't escape it — even a `z-index: 9999` child can't outrank a sibling with `z-index: 1` of the context's parent. Contexts are created by the root element, `position` + `z-index != auto`, `opacity < 1`, `transform`, `filter`, `will-change`, `isolation: isolate`, and more.",
    ".isolated { isolation: isolate; } /* forces a new context without side effects */",
  ),
  q(
    "css-m-6",
    "CSS",
    "Medium",
    "Transitions",
    "Why don't some property changes animate with `transition`?",
    "Only animatable properties tween — `display`, `visibility`, and `content` traditionally jump. Also, a transition needs a defined starting value; if the property is `auto` (like `height: auto`), the browser can't interpolate. Common workarounds: animate `opacity` + `transform` instead of `display`, use `max-height` with a large fixed value, or use `@starting-style` and `interpolate-size: allow-keywords` in modern browsers.",
    ".fade { transition: opacity 200ms ease; }\n.fade.hidden { opacity: 0; pointer-events: none; }",
  ),
  q(
    "css-m-7",
    "CSS",
    "Medium",
    "Animations",
    "What is the difference between `transition` and `@keyframes` animation?",
    "Transitions animate between two states triggered by a change (class toggle, hover). Keyframe animations run on their own timeline with multiple intermediate steps, can loop, and can be paused. Use transitions for state changes, animations for loading spinners, attention loops, and complex multi-step motion.",
    "@keyframes spin { to { transform: rotate(360deg); } }\n.spinner { animation: spin 1s linear infinite; }",
  ),
  q(
    "css-m-8",
    "CSS",
    "Medium",
    "Variables",
    "How do CSS custom properties work?",
    "Custom properties (CSS variables) are declared with a `--` prefix and read with `var()`. They cascade and inherit like normal properties and can be overridden per scope, which makes them ideal for theming. They can be updated at runtime via JavaScript with `element.style.setProperty`.",
    ":root { --primary: #6366f1; }\n[data-theme='dark'] { --primary: #a78bfa; }\n.btn { background: var(--primary); }",
  ),
  q(
    "css-m-9",
    "CSS",
    "Medium",
    "Layout",
    "How do you build a responsive card grid without media queries?",
    "Use `grid-template-columns: repeat(auto-fit, minmax(MIN, 1fr))`. Cards stay at least `MIN` wide and reflow into as many columns as fit. It's a single line that adapts from mobile to ultra-wide screens.",
    ".cards { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); }",
  ),
  q(
    "css-m-10",
    "CSS",
    "Medium",
    "Selectors",
    "What does `:not()` do and what are its limits?",
    "`:not()` matches elements that don't match the selector list inside. Modern `:not()` accepts complex selectors and multiple arguments. Its specificity equals that of its most specific argument, which can surprise people. It doesn't affect matching order.",
    "li:not(.active):not(:last-child) { border-bottom: 1px solid #eee; }",
  ),
  q(
    "css-m-11",
    "CSS",
    "Medium",
    "Selectors",
    "What is `:nth-child()` vs `:nth-of-type()`?",
    "`:nth-child(n)` matches an element that is the nth child of its parent regardless of type. `:nth-of-type(n)` counts only siblings of the same tag. If your markup mixes elements, `:nth-of-type` is often what you actually want.",
    "article p:nth-of-type(2) { font-weight: bold; }",
  ),
  q(
    "css-m-12",
    "CSS",
    "Medium",
    "Responsive",
    "What is `object-fit` and when do you use it?",
    "`object-fit` controls how an `<img>` or `<video>` fills its box when its intrinsic aspect ratio differs from the box. `cover` crops to fill, `contain` fits inside letterboxed, `fill` stretches, `none` keeps original. Pair with `object-position` for cropping control.",
    ".avatar { width: 64px; height: 64px; object-fit: cover; border-radius: 50%; }",
  ),
  q(
    "css-m-13",
    "CSS",
    "Medium",
    "Positioning",
    "How does `position: sticky` work?",
    "The element behaves as `relative` until its scroll container crosses a threshold you set (e.g. `top: 0`), at which point it becomes `fixed` to the container until its parent scrolls out of view. It's scoped to the nearest scrolling ancestor, and any ancestor with `overflow: hidden|auto|scroll` becomes that container — a common cause of 'my sticky doesn't stick'.",
    ".table-header { position: sticky; top: 0; background: white; }",
  ),
  q(
    "css-m-14",
    "CSS",
    "Medium",
    "BEM",
    "What is BEM and why use it?",
    "BEM (Block, Element, Modifier) is a naming convention: `.block`, `.block__element`, `.block--modifier`. It keeps specificity flat (everything is a single class), makes components self-contained, and prevents style leakage across the app. Widely used before utility-first CSS and still valuable in component libraries.",
    '<div class="card card--featured">\n  <h3 class="card__title">Hi</h3>\n</div>',
  ),
  q(
    "css-m-15",
    "CSS",
    "Medium",
    "Performance",
    "Which CSS properties are cheap to animate?",
    "`transform` and `opacity` are the fastest because they're handled entirely on the compositor thread — no layout or paint. Animating properties that trigger layout (`width`, `top`, `margin`) or paint (`background-color`) is much more expensive. Add `will-change: transform` when you know an element will animate, but sparingly — it consumes memory.",
    ".slide { transition: transform 300ms ease; will-change: transform; }\n.slide.active { transform: translateX(0); }",
  ),
  q(
    "css-m-16",
    "CSS",
    "Medium",
    "Filters",
    "What does `backdrop-filter` do?",
    "`backdrop-filter` applies a filter (blur, saturation, brightness) to the area *behind* an element, creating the frosted-glass effect popular in iOS and macOS UIs. The element itself needs a translucent background for the effect to show through.",
    ".glass { background: hsl(0 0% 100% / 0.15); backdrop-filter: blur(12px) saturate(180%); }",
  ),
  q(
    "css-m-17",
    "CSS",
    "Medium",
    "Grid",
    "How do you place a grid item that spans multiple columns?",
    "Use `grid-column` (and `grid-row`) with `span N` or explicit line numbers. You can also give the item a name and place it in a named area.",
    ".featured { grid-column: span 2; grid-row: span 2; }",
  ),
  q(
    "css-m-18",
    "CSS",
    "Medium",
    "Layout",
    "What are logical properties?",
    "Logical properties reference the flow direction rather than physical sides — `margin-inline`, `padding-block`, `border-inline-start`. They make layouts adapt automatically to RTL or vertical writing modes. Prefer them over `margin-left/right` in modern layouts.",
    ".card { padding-block: 12px; padding-inline: 20px; }",
  ),
  q(
    "css-m-19",
    "CSS",
    "Medium",
    "Colors",
    "What is `currentColor`?",
    "`currentColor` is a keyword that resolves to the element's current `color` value. It's incredibly useful for SVG icons, borders, and outlines that should match the text color automatically as themes or hover states change.",
    ".btn { color: white; border: 1px solid currentColor; }\n.btn svg { fill: currentColor; }",
  ),
  q(
    "css-m-20",
    "CSS",
    "Medium",
    "Accessibility",
    "How do you hide content visually but keep it accessible to screen readers?",
    "Use a 'visually hidden' utility that clips the element to zero size without setting `display: none` or `visibility: hidden` (both of which remove it from the accessibility tree). This is essential for skip links, icon-button labels, and form context.",
    ".sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }",
  ),
  q(
    "css-m-21",
    "CSS",
    "Medium",
    "Selectors",
    "What is the difference between `:focus` and `:focus-visible`?",
    "`:focus` matches whenever an element is focused, including by mouse click — leading to focus rings that look like bugs to users. `:focus-visible` only matches when the browser thinks a focus indicator is needed (usually keyboard focus). Style keyboard focus loudly and leave mouse focus alone.",
    "button:focus { outline: none; }\nbutton:focus-visible { outline: 2px solid #6366f1; outline-offset: 2px; }",
  ),
  q(
    "css-m-22",
    "CSS",
    "Medium",
    "Layout",
    "How does `aspect-ratio` help layouts?",
    "`aspect-ratio` locks a box to a width:height ratio without needing the old padding-hack. Perfect for embedded videos, thumbnails, and hero images so the layout doesn't jump as content loads.",
    ".thumb { aspect-ratio: 16 / 9; width: 100%; object-fit: cover; }",
  ),
  q(
    "css-m-23",
    "CSS",
    "Medium",
    "Selectors",
    "What does `:is()` do?",
    "`:is()` accepts a selector list and matches any element that matches one of them. It flattens verbose rules and takes the specificity of its most specific argument. Great for reducing repetition when styling headings or interactive elements.",
    ":is(h1, h2, h3) { line-height: 1.2; }",
  ),
  q(
    "css-m-24",
    "CSS",
    "Medium",
    "Selectors",
    "What is `:where()` and how is it different from `:is()`?",
    "`:where()` matches like `:is()` but has zero specificity — the entire pseudo-class contributes nothing. That makes it ideal for design-system defaults you want to be trivially overridable.",
    ":where(button, [role='button']) { cursor: pointer; }",
  ),
  q(
    "css-m-25",
    "CSS",
    "Medium",
    "Flexbox",
    "What does `align-items` vs `align-self` do?",
    "`align-items` sets the default cross-axis alignment for all children of a flex container. `align-self` overrides that for a specific child, letting one item align differently (e.g. stretch by default, but pin one item to `flex-end`).",
    ".row { display: flex; align-items: center; }\n.row .cta { align-self: flex-end; }",
  ),
  q(
    "css-m-26",
    "CSS",
    "Medium",
    "Animations",
    "What is `animation-fill-mode`?",
    "It controls the styles applied outside the animation's active period. `forwards` retains the last keyframe after the animation ends, `backwards` applies the first keyframe during the delay, and `both` does both. Without it, elements snap back to their non-animated state.",
    ".fade-in { animation: fadeIn 400ms ease forwards; }\n@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }",
  ),
  q(
    "css-m-27",
    "CSS",
    "Medium",
    "Responsive",
    "What is `clamp()`?",
    "`clamp(min, preferred, max)` returns the preferred value clamped between min and max. It's the modern way to build fluid typography and spacing — a font size that scales with the viewport but never gets too small or too big, without media queries.",
    "h1 { font-size: clamp(1.5rem, 2vw + 1rem, 3rem); }",
  ),
  q(
    "css-m-28",
    "CSS",
    "Medium",
    "Selectors",
    "What does the general sibling combinator `~` match?",
    "`A ~ B` matches every `B` that is a later sibling of `A` (same parent, appears after). The adjacent sibling `A + B` only matches the immediately following sibling.",
    "h2 ~ p { color: #666; } /* every paragraph after any h2 */",
  ),
  q(
    "css-m-29",
    "CSS",
    "Medium",
    "Layout",
    "What is `contain` and why use it?",
    "The `contain` property tells the browser that an element's layout, style, or paint is independent of the rest of the page. That lets the browser skip work when things change elsewhere, improving performance for large lists and widgets.",
    ".card { contain: content; }",
  ),
  q(
    "css-m-30",
    "CSS",
    "Medium",
    "Fonts",
    "What is `font-display: swap`?",
    "It controls how a web font renders while it's loading. `swap` shows the fallback immediately and swaps in the web font when it arrives, avoiding invisible text (FOIT). Combined with `size-adjust` and matching fallback metrics, it minimizes layout shift.",
    "@font-face { font-family: 'Inter'; src: url(/inter.woff2) format('woff2'); font-display: swap; }",
  ),
  q(
    "css-m-31",
    "CSS",
    "Medium",
    "Grid",
    "What are named grid areas?",
    "You can name grid areas with `grid-template-areas` and place items with `grid-area: <name>`. It makes layouts read like ASCII art and lets you rearrange the whole page for different breakpoints by changing the template alone.",
    ".layout { display: grid; grid-template-areas: 'nav main' 'nav aside'; grid-template-columns: 200px 1fr; }\n.nav { grid-area: nav; }",
  ),
  q(
    "css-m-32",
    "CSS",
    "Medium",
    "Colors",
    "What is `color-mix()`?",
    "`color-mix()` blends two colors in a chosen color space, returning a new color. Great for hover states derived from a base token, or interpolating between semantic colors without hand-writing shades.",
    ".btn:hover { background: color-mix(in oklch, var(--primary) 85%, black); }",
  ),
  q(
    "css-m-33",
    "CSS",
    "Medium",
    "Variables",
    "Can CSS custom properties be animated with `transition`?",
    "By default no, because their type is unknown. Register them via `@property` with a syntax and initial value, and browsers can interpolate them just like normal properties.",
    "@property --shade { syntax: '<color>'; inherits: false; initial-value: #fff; }\n.card { transition: --shade 300ms; }",
  ),
  q(
    "css-m-34",
    "CSS",
    "Medium",
    "Positioning",
    "Why can `transform` on an ancestor break `position: fixed` children?",
    "A `transform` (non-`none`) or `filter` on an ancestor makes that ancestor the containing block for `fixed` descendants — the child positions to the ancestor instead of the viewport. It's a common surprise when tooltips or modals inside animated cards suddenly misplace.",
    "/* Move the fixed element out of the transformed ancestor with a portal */",
  ),
  q(
    "css-m-35",
    "CSS",
    "Medium",
    "Selectors",
    "What does `:root` refer to?",
    "`:root` matches the document root — in HTML always `<html>`. Its specificity is higher than the `html` type selector, so it's the conventional place to declare global custom properties.",
    ":root { --radius: 12px; }",
  ),

  // ============ CSS ADVANCED ============
  q(
    "css-a-1",
    "CSS",
    "Advanced",
    "Container Queries",
    "What are container queries and when do you use them?",
    "Container queries let a component style itself based on the size of its own container instead of the viewport. Declare `container-type: inline-size` on a parent and query with `@container (min-width: 400px) { … }`. They enable truly reusable components that adapt correctly whether placed in a sidebar or a full-width hero.",
    ".card { container-type: inline-size; }\n@container (min-width: 400px) { .card__body { display: grid; grid-template-columns: 1fr 2fr; } }",
  ),
  q(
    "css-a-2",
    "CSS",
    "Advanced",
    "Selectors",
    "What does the `:has()` selector do?",
    "`:has()` is the long-awaited parent selector: it matches an element that contains a descendant (or sibling) matching the argument. You can style a form when it has an invalid field, a card when it has an image, or a label when its associated input is checked — no JavaScript.",
    "form:has(input:invalid) .submit { opacity: 0.5; pointer-events: none; }\n.card:has(img) { padding-top: 0; }",
  ),
  q(
    "css-a-3",
    "CSS",
    "Advanced",
    "Cascade Layers",
    "What are cascade layers (`@layer`)?",
    "Cascade layers give you explicit control over precedence groups. Layers declared later win over earlier ones regardless of specificity within them. Perfect for organizing resets, framework styles, components, and utilities without specificity wars.",
    "@layer reset, base, components, utilities;\n@layer components { .btn { padding: 8px 16px; } }",
  ),
  q(
    "css-a-4",
    "CSS",
    "Advanced",
    "Performance",
    "What causes layout thrashing and how do you fix it?",
    "Layout thrashing happens when JavaScript reads a layout property (`offsetWidth`), then writes a style, then reads again — forcing repeated synchronous layout recalculations. Batch all reads first, then all writes. Use `requestAnimationFrame` for style writes and `IntersectionObserver` / `ResizeObserver` instead of manual scroll/resize measurement.",
    "// bad: read/write/read/write ...\n// good:\nconst widths = els.map(e => e.offsetWidth);\nels.forEach((e, i) => e.style.width = widths[i] + 'px');",
  ),
  q(
    "css-a-5",
    "CSS",
    "Advanced",
    "Rendering",
    "What are `content-visibility` and `contain-intrinsic-size`?",
    "`content-visibility: auto` tells the browser to skip rendering off-screen sections until they scroll into view — huge wins on long pages. Because the browser doesn't know the size, pair it with `contain-intrinsic-size` to reserve space and prevent scroll jumps.",
    "section { content-visibility: auto; contain-intrinsic-size: 800px; }",
  ),
  q(
    "css-a-6",
    "CSS",
    "Advanced",
    "Animations",
    "What are Scroll-driven animations?",
    "Modern CSS supports `animation-timeline: scroll()` and `view()` so keyframe animations progress with scroll position or an element's entry into the viewport — no scroll-listener JS. Great for progress bars, parallax, and reveal effects.",
    "@keyframes progress { to { width: 100%; } }\n.bar { animation: progress linear; animation-timeline: scroll(root); }",
  ),
  q(
    "css-a-7",
    "CSS",
    "Advanced",
    "Colors",
    "What is a wide-gamut color space like OKLCH?",
    "OKLCH is a perceptual color space where equal changes in L, C, or H produce equal perceived changes — unlike HSL, whose lightness varies wildly across hues. Wide-gamut spaces (`display-p3`, `rec2020`) allow more saturated colors on capable displays. Design systems benefit from consistent contrast when tokens are defined in OKLCH.",
    ":root { --primary: oklch(0.65 0.2 260); }",
  ),
  q(
    "css-a-8",
    "CSS",
    "Advanced",
    "Layout",
    "How does `subgrid` work and why is it useful?",
    "A subgrid inherits its parent grid's tracks instead of defining its own. That lets deeply nested items align to the same lines — for example, cards in a grid whose titles, images, and CTAs align across rows even if content lengths differ.",
    ".cards { display: grid; grid-template-columns: repeat(3, 1fr); grid-template-rows: auto 1fr auto; }\n.card { display: grid; grid-row: span 3; grid-template-rows: subgrid; }",
  ),
  q(
    "css-a-9",
    "CSS",
    "Advanced",
    "Stacking",
    "How would you debug an element that won't stack above another?",
    "Check whether either element is inside a stacking context that traps it. Look up the DOM for ancestors with `transform`, `filter`, `opacity < 1`, `isolation: isolate`, `will-change`, or `position` + `z-index`. Once you find the trapping context, either move the element out of it (portal) or raise the context itself.",
    ".ctx { isolation: isolate; } /* create a context to compare against */",
  ),
  q(
    "css-a-10",
    "CSS",
    "Advanced",
    "Modern",
    "What is `@starting-style` and `interpolate-size`?",
    "`@starting-style` defines the styles an element should transition *from* the first time it appears in the DOM — enabling enter animations without JS. `interpolate-size: allow-keywords` teaches the browser to animate to/from `auto` sizes so accordions can transition height fluidly.",
    ".toast { transition: opacity 200ms, transform 200ms; }\n@starting-style { .toast { opacity: 0; transform: translateY(-8px); } }",
  ),
  q(
    "css-a-11",
    "CSS",
    "Advanced",
    "Cascade",
    "What is the specificity of `:where()` vs `:is()` again — and why does it matter for design systems?",
    "`:is()` inherits its most specific argument's specificity, which can escalate rules unexpectedly. `:where()` contributes zero, so wrapping default component styles in `:where()` lets consumers override them with plain class selectors. This is the modern way to ship 'opinionated but overridable' defaults.",
    ":where(.btn) { padding: 8px 16px; } /* consumer's .btn { padding: 0; } wins */",
  ),
  q(
    "css-a-12",
    "CSS",
    "Advanced",
    "Custom Properties",
    "Explain the difference between `--x: 10` and `--x: 10px` when used in `calc()`.",
    "Custom properties are just strings until used. `--x: 10` stored as a unitless number can be multiplied by a unit via `calc(var(--x) * 1px)`. `--x: 10px` already has a unit and can be used directly. Registering the property with `@property` gives it a real type and enables interpolation and validation.",
    "@property --gap { syntax: '<length>'; inherits: true; initial-value: 8px; }\n.row { gap: var(--gap); }",
  ),
  q(
    "css-a-13",
    "CSS",
    "Advanced",
    "Compatibility",
    "How do you build progressive enhancement with `@supports`?",
    "`@supports` gates CSS on feature support. Ship a solid fallback outside the block and enhanced styles inside. Combine it with `:has()` or subgrid to give modern browsers richer layouts while older ones still work.",
    ".grid { display: flex; }\n@supports (display: grid) { .grid { display: grid; grid-template-columns: repeat(3, 1fr); } }",
  ),
  q(
    "css-a-14",
    "CSS",
    "Advanced",
    "Performance",
    "What does `will-change` actually do, and what are its costs?",
    "`will-change` hints to the browser to promote an element to its own layer before an animation starts, avoiding a paint hitch at the first frame. But layers consume memory and GPU resources, and applying `will-change` to many elements or leaving it on indefinitely hurts performance. Add it just before the animation and remove it after.",
    ".modal { will-change: transform, opacity; }",
  ),
  q(
    "css-a-15",
    "CSS",
    "Advanced",
    "Motion",
    "What is `prefers-reduced-motion` and how should you use it?",
    "It's a media feature reflecting the OS 'reduce motion' setting. Users who set it are prone to motion sickness or find animations distracting. Respect it by disabling or shortening animations and transitions.",
    "@media (prefers-reduced-motion: reduce) { *, *::before, *::after { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; } }",
  ),
  q(
    "css-a-16",
    "CSS",
    "Advanced",
    "Selectors",
    "How does `:nth-child(An+B of S)` work?",
    "The `of S` syntax filters the sibling set to elements matching selector `S` before counting. `li:nth-child(2n of .active)` matches every second `.active` item — not every second `li` that also happens to be active.",
    "li:nth-child(2n of .active) { background: yellow; }",
  ),
  q(
    "css-a-17",
    "CSS",
    "Advanced",
    "Modern",
    "What is the CSS `@scope` rule?",
    "`@scope` scopes selectors between a root and an optional lower boundary, so styles apply within a subtree without leaking. It's a native alternative to CSS-in-JS scoping and shadow DOM for many use cases.",
    "@scope (.card) to (.card .comments) { p { color: #333; } }",
  ),
  q(
    "css-a-18",
    "CSS",
    "Advanced",
    "Rendering",
    "What causes a paint vs a composite in the browser rendering pipeline?",
    "The pipeline is Style → Layout → Paint → Composite. Changing geometry (`width`, `top`) triggers layout + paint + composite. Changing colors triggers paint + composite. Changing `transform` or `opacity` only re-composites (if the element is on its own layer). Animate the last group for 60fps.",
    "/* animate this: */ .x { transform: translateX(0); transition: transform 300ms; }",
  ),
  q(
    "css-a-19",
    "CSS",
    "Advanced",
    "Layout",
    "Explain intrinsic sizing keywords: `min-content`, `max-content`, `fit-content`.",
    "`min-content` shrinks to the smallest possible width without overflow (widest word). `max-content` grows to the width the content prefers with no wrapping. `fit-content(x)` clamps `max-content` at `x`. Use them in grid tracks and widths for content-driven sizing.",
    ".tag { width: fit-content; padding: 4px 8px; }",
  ),
  q(
    "css-a-20",
    "CSS",
    "Advanced",
    "Modern",
    "What is Anchor Positioning?",
    "The new anchor positioning API (`anchor-name`, `position-anchor`, `anchor()`) lets an absolutely positioned element position itself relative to another element that isn't its containing-block ancestor. Perfect for tooltips, popovers, and menus without JS positioning logic.",
    ".btn { anchor-name: --btn; }\n.tip { position: absolute; top: anchor(--btn bottom); left: anchor(--btn center); }",
  ),

  // ============ HTML BASIC ============
  q(
    "html-b-1",
    "HTML",
    "Basic",
    "Semantics",
    "What is semantic HTML?",
    "Semantic HTML uses elements that describe the meaning of their content rather than just its appearance: `<header>`, `<nav>`, `<main>`, `<article>`, `<section>`, `<aside>`, `<footer>`. Screen readers, search engines, and reader-mode tools rely on them to understand structure. Semantic markup also reduces the need for extra ARIA and improves SEO.",
    "<article>\n  <header><h1>Title</h1></header>\n  <p>Body…</p>\n  <footer>By Author</footer>\n</article>",
  ),
  q(
    "html-b-2",
    "HTML",
    "Basic",
    "Structure",
    "What is the purpose of the `<!DOCTYPE html>` declaration?",
    "It tells the browser to render the page in standards mode. Without it, browsers fall back to quirks mode, which emulates buggy legacy behavior (odd box sizing, table centering) for compatibility with 1990s pages. Always start HTML files with `<!DOCTYPE html>`.",
    '<!DOCTYPE html>\n<html lang="en">…</html>',
  ),
  q(
    "html-b-3",
    "HTML",
    "Basic",
    "Structure",
    "What does the `lang` attribute on `<html>` do?",
    "It declares the document's language, helping screen readers use the correct pronunciation, search engines target regional results, and tools like translators and spell-checkers pick the right dictionary. Use a valid BCP-47 tag: `en`, `en-US`, `pt-BR`.",
    '<html lang="en">',
  ),
  q(
    "html-b-4",
    "HTML",
    "Basic",
    "Meta",
    "What is the viewport meta tag and why is it required?",
    "It tells mobile browsers how to size the layout viewport. Without it, mobile Safari and Chrome render pages at ~980px and scale them down, making text tiny. `width=device-width, initial-scale=1` maps the layout viewport to the device width for responsive design.",
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
  ),
  q(
    "html-b-5",
    "HTML",
    "Basic",
    "Attributes",
    "What is the difference between attributes and properties?",
    "Attributes are declared in HTML markup and appear in the source. Properties are values on the DOM object. Some attributes and properties sync (like `id`), some don't (`value` on `<input>` — the attribute is the default, the property is the current value). Use `getAttribute()` for the markup and `element.value` for the live state.",
    "<input value=\"hello\">\n// input.value = 'edited'; getAttribute('value') still 'hello'",
  ),
  q(
    "html-b-6",
    "HTML",
    "Basic",
    "Semantics",
    "What is the difference between `<div>` and `<section>`?",
    "`<div>` is a generic, meaningless container — use it purely for layout hooks. `<section>` is a semantic grouping of related content that would normally have a heading. If you can't give it a heading, it should probably be a `<div>`.",
    "<section>\n  <h2>Latest posts</h2>\n  <ul>…</ul>\n</section>",
  ),
  q(
    "html-b-7",
    "HTML",
    "Basic",
    "Forms",
    "What does the `label` element do?",
    "It associates a text label with a form control, so clicking the label focuses the input and screen readers announce the label together with the control. Associate by wrapping the input or with `for`/`id`.",
    '<label for="email">Email</label>\n<input id="email" type="email">',
  ),
  q(
    "html-b-8",
    "HTML",
    "Basic",
    "Forms",
    "Name several `<input>` types added in HTML5.",
    "`email`, `url`, `tel`, `number`, `range`, `date`, `time`, `datetime-local`, `color`, `search`. They provide built-in validation, appropriate on-screen keyboards on mobile, and native pickers — reducing the need for custom JS controls.",
    '<input type="email" required>\n<input type="date">',
  ),
  q(
    "html-b-9",
    "HTML",
    "Basic",
    "Images",
    "Why is the `alt` attribute important?",
    'It describes an image for users who can\'t see it: screen-reader users, users on slow connections where images fail, and search engines. Meaningful images need descriptive alt text; purely decorative images should use `alt=""` so screen readers skip them.',
    '<img src="chart.png" alt="Bar chart: 2024 revenue by quarter">\n<img src="divider.svg" alt="">',
  ),
  q(
    "html-b-10",
    "HTML",
    "Basic",
    "Links",
    'What does `target="_blank"` do and what security issue does it have?',
    'It opens the link in a new tab or window. Historically, the new window could access `window.opener` and manipulate the original page (reverse tabnabbing). Modern browsers default `noopener` on `_blank`, but it\'s still best practice to add `rel="noopener noreferrer"` explicitly.',
    '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Docs</a>',
  ),
  q(
    "html-b-11",
    "HTML",
    "Basic",
    "Semantics",
    "What is the difference between `<b>` and `<strong>` (or `<i>` and `<em>`)?",
    "`<b>` and `<i>` are purely presentational (bold/italic) and carry no semantic meaning. `<strong>` marks strong importance and `<em>` marks stress emphasis — screen readers may change intonation. Prefer semantic tags unless you truly just need visual weight without meaning.",
    "<p><strong>Warning:</strong> this is <em>irreversible</em>.</p>",
  ),
  q(
    "html-b-12",
    "HTML",
    "Basic",
    "Lists",
    "When do you use `<ul>` vs `<ol>` vs `<dl>`?",
    "`<ul>` is an unordered list — bullet points where sequence doesn't matter. `<ol>` is ordered — the position of items matters (steps, rankings). `<dl>` is a description list of term/definition pairs (`<dt>` + `<dd>`).",
    "<ol><li>Preheat</li><li>Mix</li><li>Bake</li></ol>",
  ),
  q(
    "html-b-13",
    "HTML",
    "Basic",
    "Forms",
    "What is the `placeholder` attribute — and what shouldn't it be?",
    "`placeholder` shows hint text inside an empty input. It disappears once typing starts, so it must NOT be used as the label — users forget what the field is for and screen readers may skip it. Always pair with a real `<label>`.",
    '<label for="q">Search</label>\n<input id="q" placeholder="e.g. gradient">',
  ),
  q(
    "html-b-14",
    "HTML",
    "Basic",
    "Meta",
    "What are Open Graph meta tags?",
    "Open Graph tags (`og:title`, `og:description`, `og:image`, `og:url`, `og:type`) tell social platforms how to render link previews. Twitter has its own `twitter:*` set. Ship them on every shareable page for good social presence.",
    '<meta property="og:title" content="…">\n<meta property="og:image" content="https://…/hero.jpg">',
  ),
  q(
    "html-b-15",
    "HTML",
    "Basic",
    "Images",
    'What does the `loading="lazy"` attribute do?',
    "It defers loading of below-the-fold images and iframes until they're near the viewport. It's a one-attribute performance win with no JS. Don't lazy-load your hero image — it delays LCP.",
    '<img src="thumb.jpg" alt="…" loading="lazy" width="320" height="180">',
  ),
  q(
    "html-b-16",
    "HTML",
    "Basic",
    "Semantics",
    "When should you use `<article>`?",
    "`<article>` marks a self-contained piece of content that would make sense on its own — a blog post, a comment, a product card in a listing. If you could syndicate it or share it independently, it's an article.",
    "<article>\n  <h2>Post title</h2>\n  <p>…</p>\n</article>",
  ),
  q(
    "html-b-17",
    "HTML",
    "Basic",
    "Forms",
    "What does the `required` attribute do?",
    'It marks a form control as required. The browser blocks submission and shows a native validation bubble if it\'s empty. Combine with `type` for validation (`type="email"` + `required`) to get free client-side checks.',
    '<input type="email" required>',
  ),
  q(
    "html-b-18",
    "HTML",
    "Basic",
    "Structure",
    "What is the purpose of the `<head>` element?",
    "It contains metadata about the document that isn't rendered directly: title, charset, viewport, links to stylesheets, scripts, meta tags for SEO and social sharing. The browser processes it before rendering the body.",
    '<head>\n  <meta charset="utf-8">\n  <title>Page</title>\n</head>',
  ),
  q(
    "html-b-19",
    "HTML",
    "Basic",
    "Data Attributes",
    "What are `data-*` attributes?",
    "Custom attributes prefixed with `data-` let you attach app-specific data to elements without inventing non-standard attributes. Read them in JS via `element.dataset.name`. Common uses: JS hooks, analytics tags, per-item state.",
    '<button data-action="delete" data-id="42">Delete</button>\n// btn.dataset.action === \'delete\'',
  ),
  q(
    "html-b-20",
    "HTML",
    "Basic",
    "Semantics",
    "What is the difference between `<header>` and `<h1>`?",
    "`<header>` is a landmark region for introductory content (logo, nav, page title). `<h1>` is the top-level heading of a document or section. A page can have multiple `<header>` regions (one per section) but should typically have one `<h1>`.",
    "<header>\n  <h1>Docs</h1>\n  <nav>…</nav>\n</header>",
  ),
  q(
    "html-b-21",
    "HTML",
    "Basic",
    "Media",
    "What are `<picture>` and `<source>` used for?",
    "`<picture>` lets you deliver different image assets based on media queries or formats. Browsers pick the first matching `<source>`; the `<img>` inside is the fallback. Perfect for art-directed responsive images and modern-format delivery (AVIF/WebP with JPG fallback).",
    '<picture>\n  <source type="image/avif" srcset="hero.avif">\n  <source type="image/webp" srcset="hero.webp">\n  <img src="hero.jpg" alt="…">\n</picture>',
  ),
  q(
    "html-b-22",
    "HTML",
    "Basic",
    "Meta",
    'What does `<meta charset="utf-8">` do?',
    "It declares the document's character encoding. UTF-8 covers virtually every language and emoji. Without a correct charset, browsers guess and may mis-render accented characters or symbols. Place it in the first 1024 bytes of `<head>`.",
    '<meta charset="utf-8">',
  ),
  q(
    "html-b-23",
    "HTML",
    "Basic",
    "Links",
    "What does the `download` attribute on `<a>` do?",
    "It tells the browser to download the linked file instead of navigating to it, and optionally to save it with a specified filename. Same-origin only for the filename hint.",
    '<a href="/report.pdf" download="annual-report.pdf">Download</a>',
  ),
  q(
    "html-b-24",
    "HTML",
    "Basic",
    "Structure",
    "What is the difference between `<script>` and `<script defer>` and `<script async>`?",
    "A plain `<script>` blocks HTML parsing while it downloads and runs. `defer` downloads in parallel and runs after parsing, preserving order — perfect for scripts that touch the DOM. `async` downloads in parallel and runs as soon as available, without ordering — good for independent analytics.",
    '<script src="app.js" defer></script>',
  ),
  q(
    "html-b-25",
    "HTML",
    "Basic",
    "Forms",
    'What is the `<button type="button">` gotcha?',
    'Inside a `<form>`, `<button>` defaults to `type="submit"`. If you use one for cancel or a modal trigger without setting `type="button"`, clicking it submits the form. Always set an explicit type on non-submit buttons.',
    '<button type="button" onclick="open()">Open</button>',
  ),

  // ============ HTML MEDIUM ============
  q(
    "html-m-1",
    "HTML",
    "Medium",
    "ARIA",
    "What are ARIA roles and when do you need them?",
    'ARIA roles (`role="button"`, `role="dialog"`, `role="navigation"`) tell assistive tech what an element is when native semantics don\'t. Rule #1: prefer native elements (`<button>`) over ARIA (`<div role="button">`). Use ARIA to fill gaps, not to reinvent semantics that HTML already has.',
    '<div role="tablist">\n  <button role="tab" aria-selected="true">One</button>\n</div>',
  ),
  q(
    "html-m-2",
    "HTML",
    "Medium",
    "ARIA",
    "What is `aria-label` vs `aria-labelledby`?",
    "`aria-label` gives an element an accessible name from a string. `aria-labelledby` references the ID of another element whose text becomes the name — great when the label is already visible elsewhere on screen and you want them to stay in sync.",
    '<button aria-label="Close">×</button>\n<div role="dialog" aria-labelledby="t"><h2 id="t">Delete?</h2></div>',
  ),
  q(
    "html-m-3",
    "HTML",
    "Medium",
    "Forms",
    "What is `<fieldset>` and `<legend>`?",
    "`<fieldset>` groups related form controls and `<legend>` provides a caption. Screen readers announce the legend for each control in the group — essential for related radio buttons or checkbox sets so users hear the group's purpose.",
    '<fieldset>\n  <legend>Notify me by</legend>\n  <label><input type="radio" name="n"> Email</label>\n  <label><input type="radio" name="n"> SMS</label>\n</fieldset>',
  ),
  q(
    "html-m-4",
    "HTML",
    "Medium",
    "Accessibility",
    "How do you make a `<div>` behave like an interactive button?",
    'You would need `role="button"`, `tabindex="0"`, click AND keyboard (Enter/Space) handlers, focus styles, and `aria-disabled` when relevant. Instead: use `<button type="button">` and get all of that for free. Reserve div-buttons for genuinely custom widgets that can\'t be built with real elements.',
    '<button type="button" class="btn">Save</button>',
  ),
  q(
    "html-m-5",
    "HTML",
    "Medium",
    "Meta",
    "What is a canonical link and why does it matter for SEO?",
    '`<link rel="canonical" href="…">` tells search engines which URL is the definitive version of a page when multiple URLs would show the same content (e.g. with tracking params). It consolidates ranking signals to one URL.',
    '<link rel="canonical" href="https://example.com/blog/post">',
  ),
  q(
    "html-m-6",
    "HTML",
    "Medium",
    "Semantics",
    "When do you use `<main>`?",
    "`<main>` marks the primary content of the page, excluding headers, footers, and sidebars. There should be exactly one `<main>` per page. Screen-reader users can jump to it via a landmark shortcut, and 'skip to content' links target it.",
    '<a class="sr-only" href="#main">Skip to content</a>\n<main id="main">…</main>',
  ),
  q(
    "html-m-7",
    "HTML",
    "Medium",
    "Forms",
    "What does the `autocomplete` attribute do?",
    "It tells browsers what type of value a field expects, so autofill can suggest the right one and password managers can save it correctly. Use standard tokens: `name`, `email`, `street-address`, `postal-code`, `current-password`, `one-time-code`. Autofill improves conversion — don't disable it without a reason.",
    '<input autocomplete="email" type="email">\n<input autocomplete="one-time-code" inputmode="numeric">',
  ),
  q(
    "html-m-8",
    "HTML",
    "Medium",
    "Media",
    "What is the `srcset` attribute on `<img>`?",
    "`srcset` lets you provide multiple image files and the browser picks the best for the current viewport and pixel density. Combined with `sizes`, it delivers appropriately sized images without downloading a giant one on mobile.",
    '<img src="h-800.jpg" srcset="h-400.jpg 400w, h-800.jpg 800w, h-1600.jpg 1600w" sizes="(min-width: 768px) 50vw, 100vw" alt="…">',
  ),
  q(
    "html-m-9",
    "HTML",
    "Medium",
    "Tables",
    "What are `<thead>`, `<tbody>`, and `<tfoot>` for?",
    "They group table rows semantically. Screen readers can announce column headers repeatedly for each data row, and browsers can repeat `<thead>` on print pagination. Also enables sticky headers and separate styling for header/footer sections.",
    "<table>\n  <thead><tr><th>Name</th></tr></thead>\n  <tbody><tr><td>Ada</td></tr></tbody>\n</table>",
  ),
  q(
    "html-m-10",
    "HTML",
    "Medium",
    "Accessibility",
    "What are landmark regions?",
    'Landmarks are structural regions announced to assistive tech: `<header>` (banner), `<nav>` (navigation), `<main>` (main), `<aside>` (complementary), `<footer>` (contentinfo), `<form>` (form), and elements with `role="search"` or `role="region"` + label. Users can jump between them via keyboard shortcuts.',
    '<nav aria-label="Primary">…</nav>\n<aside aria-label="Related">…</aside>',
  ),
  q(
    "html-m-11",
    "HTML",
    "Medium",
    "APIs",
    "What is the `<dialog>` element?",
    "A native modal/non-modal dialog with built-in focus management, backdrop, and ESC-to-close (for modal). `showModal()` opens as a true modal on the top layer, above every stacking context. Style the backdrop via `dialog::backdrop`.",
    '<dialog id="d"><form method="dialog"><button>OK</button></form></dialog>\n<script>d.showModal()</script>',
  ),
  q(
    "html-m-12",
    "HTML",
    "Medium",
    "Forms",
    "What is `formnovalidate`?",
    "Placed on a submit button, it bypasses HTML5 validation for that submission — useful for 'Save draft' buttons where partial data is acceptable, while the main 'Submit' still validates.",
    '<button type="submit">Publish</button>\n<button type="submit" formnovalidate>Save draft</button>',
  ),
  q(
    "html-m-13",
    "HTML",
    "Medium",
    "Semantics",
    "What does `<figure>` and `<figcaption>` represent?",
    "`<figure>` groups content (image, chart, code block) that is referenced from the main flow, with an optional `<figcaption>` caption. Screen readers announce the caption, and it makes semantic intent explicit vs. a plain `<img>`.",
    '<figure>\n  <img src="chart.svg" alt="…">\n  <figcaption>Revenue by quarter</figcaption>\n</figure>',
  ),
  q(
    "html-m-14",
    "HTML",
    "Medium",
    "APIs",
    "What does the `<details>` and `<summary>` element do?",
    "It's a native disclosure widget: click `<summary>` to expand/collapse `<details>`. No JS needed, keyboard-accessible, and screen-reader friendly out of the box. Add `open` to render expanded by default.",
    "<details><summary>Show more</summary><p>Hidden text.</p></details>",
  ),
  q(
    "html-m-15",
    "HTML",
    "Medium",
    "Meta",
    "What are `preload`, `prefetch`, and `preconnect`?",
    "`preload` tells the browser to fetch a resource ASAP with high priority — for critical fonts and hero images. `prefetch` fetches at low priority for likely next navigations. `preconnect` opens the TCP/TLS connection to an origin early. Use them sparingly and measure impact.",
    '<link rel="preload" href="/font.woff2" as="font" type="font/woff2" crossorigin>\n<link rel="preconnect" href="https://api.example.com">',
  ),
  q(
    "html-m-16",
    "HTML",
    "Medium",
    "ARIA",
    "What is `aria-live` for?",
    "It marks a region as live so screen readers announce updates without moving focus. Use `polite` for status messages (autosave, results loaded) and `assertive` for urgent alerts (errors that need immediate attention).",
    '<div role="status" aria-live="polite">Saved</div>',
  ),
  q(
    "html-m-17",
    "HTML",
    "Medium",
    "Forms",
    "What are `pattern` and `inputmode` on inputs?",
    "`pattern` is a regex the browser validates against on submit. `inputmode` hints the on-screen keyboard type on mobile (`numeric`, `decimal`, `email`, `tel`) without changing validation. Together they give tailored input UX without a custom control.",
    '<input inputmode="numeric" pattern="[0-9]{6}" required>',
  ),
  q(
    "html-m-18",
    "HTML",
    "Medium",
    "Images",
    'What is `decoding="async"` on `<img>`?',
    'It hints the browser to decode the image off the main thread, avoiding jank when a large image appears. Pair with `loading="lazy"` for off-screen images.',
    '<img src="…" alt="…" loading="lazy" decoding="async">',
  ),
  q(
    "html-m-19",
    "HTML",
    "Medium",
    "Semantics",
    "What is `<time>` for?",
    "It marks a date/time in machine-readable form via the `datetime` attribute while showing human-friendly text. Useful for microdata, search engines, and any script that needs to parse dates from the DOM.",
    '<time datetime="2025-11-20T09:00">Nov 20, 9 AM</time>',
  ),
  q(
    "html-m-20",
    "HTML",
    "Medium",
    "APIs",
    "How do you embed a YouTube video responsively without an iframe hack?",
    "Wrap the iframe in a container with `aspect-ratio` set to the video's ratio and let the iframe fill 100% of the parent. Modern browsers respect `aspect-ratio` on the iframe directly too.",
    '.video { aspect-ratio: 16 / 9; width: 100%; }\n<iframe class="video" src="…" allowfullscreen></iframe>',
  ),

  // ============ HTML ADVANCED ============
  q(
    "html-a-1",
    "HTML",
    "Advanced",
    "APIs",
    "What is the top layer and how do `<dialog>` and popover use it?",
    "The top layer is a special browser rendering layer above every stacking context — nothing on the page can ever cover it. `dialog.showModal()` and the `popover` attribute promote elements to the top layer, solving the classic 'my modal is under this transformed navbar' problem without portals.",
    '<button popovertarget="menu">Open</button>\n<div id="menu" popover>Menu</div>',
  ),
  q(
    "html-a-2",
    "HTML",
    "Advanced",
    "Forms",
    "What is Form-Associated Custom Elements (ElementInternals)?",
    "Web components can participate in forms like native inputs by calling `this.attachInternals()` and using its API to set form value, validity, and validation messages. This closes the gap between custom widgets and the platform's form/validation model.",
    "class MyInput extends HTMLElement {\n  static formAssociated = true;\n  constructor(){ super(); this._i = this.attachInternals(); }\n  set value(v){ this._i.setFormValue(v); }\n}",
  ),
  q(
    "html-a-3",
    "HTML",
    "Advanced",
    "Performance",
    "What is `fetchpriority` on images and links?",
    '`fetchpriority="high"` or `"low"` overrides the browser\'s default resource priority. Set it to `high` on the LCP image to prioritize it above other images and scripts. Use `low` on non-critical below-the-fold images.',
    '<img src="/hero.jpg" fetchpriority="high" alt="…">',
  ),
  q(
    "html-a-4",
    "HTML",
    "Advanced",
    "Accessibility",
    "How do you build an accessible autocomplete combobox?",
    'You need a text input with `role="combobox"`, `aria-expanded`, `aria-controls` pointing to the listbox, `aria-activedescendant` for the highlighted option, arrow key handling, Enter/Escape support, and a listbox with `role="listbox"` containing `role="option"` items. Prefer a battle-tested library or the emerging `<selectlist>` element rather than rolling your own.',
    '<input role="combobox" aria-expanded="true" aria-controls="lb" aria-activedescendant="o1">\n<ul id="lb" role="listbox"><li id="o1" role="option">A</li></ul>',
  ),
  q(
    "html-a-5",
    "HTML",
    "Advanced",
    "APIs",
    "What is the difference between Shadow DOM open and closed mode?",
    "`attachShadow({ mode: 'open' })` exposes the shadow root as `element.shadowRoot`, letting outside code inspect and manipulate it. `'closed'` returns null externally, giving encapsulation. Closed mode isn't real security (JS can monkey-patch) but discourages coupling.",
    "this.attachShadow({ mode: 'open' }).innerHTML = '<style>…</style><slot></slot>';",
  ),
  q(
    "html-a-6",
    "HTML",
    "Advanced",
    "Semantics",
    "How should you structure headings for accessibility and SEO?",
    "Use a single `<h1>` per document that names the page, then nest `<h2>`–`<h6>` in order without skipping levels. Assistive tech users navigate by heading; skipped levels feel like missing chapters. Sectioning elements (`<article>`, `<section>`) do not reset the heading rank in current spec, so continue the numeric hierarchy.",
    "<h1>Post</h1>\n  <h2>Intro</h2>\n  <h2>Details</h2>\n    <h3>Subpoint</h3>",
  ),
  q(
    "html-a-7",
    "HTML",
    "Advanced",
    "Meta",
    "How would you add JSON-LD structured data to a page?",
    'Add a `<script type="application/ld+json">` in `<head>` (or body) containing schema.org JSON. Google and other search engines parse it to render rich results — Article, Product, FAQ, BreadcrumbList, Organization.',
    '<script type="application/ld+json">\n{"@context":"https://schema.org","@type":"Article","headline":"Post"}\n</script>',
  ),
  q(
    "html-a-8",
    "HTML",
    "Advanced",
    "Forms",
    "What is `enterkeyhint` on inputs?",
    "It changes the label on the mobile keyboard's Enter key: `search`, `send`, `go`, `next`, `done`, `previous`. Small polish that makes forms feel native on mobile — a search box shows a Search key instead of Enter.",
    '<input type="search" enterkeyhint="search">',
  ),
  q(
    "html-a-9",
    "HTML",
    "Advanced",
    "Performance",
    "What is the Speculation Rules API?",
    "A JSON-in-`<script>` declarative API to tell the browser which links to prerender or prefetch. Prerender fully loads and executes a page in the background; when the user clicks, navigation is instant. Use it carefully — only for high-confidence next navigations.",
    '<script type="speculationrules">\n{"prerender":[{"source":"list","urls":["/next"]}]}\n</script>',
  ),
  q(
    "html-a-10",
    "HTML",
    "Advanced",
    "APIs",
    "What is a `<template>` element?",
    "`<template>` holds inert HTML that isn't rendered or scripted until you clone and insert it. Perfect for reusable DOM fragments in web components or when instantiating list items without string concatenation.",
    "<template id=\"row\"><li><span></span></li></template>\n// document.importNode(document.getElementById('row').content, true)",
  ),
  q(
    "html-a-11",
    "HTML",
    "Advanced",
    "APIs",
    "What is `<slot>` in Shadow DOM?",
    "`<slot>` marks placeholders in a web component's shadow tree where light-DOM children projected by the consumer render. Named slots (`<slot name=\"header\">`) let you compose multiple insertion points. It's how web components achieve React-like composition.",
    '<my-card>\n  <h3 slot="header">Title</h3>\n  <p>Body</p>\n</my-card>',
  ),
  q(
    "html-a-12",
    "HTML",
    "Advanced",
    "Accessibility",
    "How do focus rings interact with `outline` and `box-shadow`?",
    "`outline` doesn't take space and can be offset with `outline-offset` — the modern, safe way to draw a focus ring. `box-shadow` also works but doesn't respect Windows High Contrast mode. Always test focus with keyboard tab, and pair `outline: transparent` with `outline-offset` so High Contrast mode can still show a ring.",
    "button:focus-visible { outline: 2px solid Highlight; outline-offset: 2px; }",
  ),
  q(
    "css-b-31",
    "CSS",
    "Basic",
    "Backgrounds",
    "How do you set a background image that covers the entire element?",
    "Use `background-image` with `background-size: cover` to scale the image to fill the box while preserving aspect ratio. Combine with `background-position: center` to keep the focal point centered and `background-repeat: no-repeat` to prevent tiling.",
    ".hero { background: url('/hero.jpg') center/cover no-repeat; }",
  ),
  q(
    "css-b-32",
    "CSS",
    "Basic",
    "Text",
    "How do you underline text on hover only?",
    "Set `text-decoration: none` in the default state and `text-decoration: underline` inside `:hover`. Use `text-underline-offset` for spacing between the text and the line.",
    "a { text-decoration: none; }\na:hover { text-decoration: underline; text-underline-offset: 3px; }",
  ),
  q(
    "css-b-33",
    "CSS",
    "Basic",
    "Overflow",
    "What does `overflow: hidden` do?",
    "It clips any content that exceeds the element's box and hides scrollbars. It also creates a new block formatting context, which is a handy side-effect for containing floats or preventing margin collapse.",
    ".card { overflow: hidden; border-radius: 12px; }",
  ),
  q(
    "css-b-34",
    "CSS",
    "Basic",
    "Borders",
    "How do you make a circle with pure CSS?",
    "Give an element equal width and height, then set `border-radius: 50%`. The percentage is relative to the box, so any square becomes a perfect circle.",
    ".avatar { width: 48px; height: 48px; border-radius: 50%; }",
  ),
  q(
    "css-b-35",
    "CSS",
    "Basic",
    "Cursor",
    "How do you change the mouse cursor for an interactive element?",
    "Use the `cursor` property. Common values are `pointer` for clickable elements, `not-allowed` for disabled controls, `grab`/`grabbing` for drag handles, and `text` for editable text areas.",
    "button { cursor: pointer; }\nbutton:disabled { cursor: not-allowed; }",
  ),
  q(
    "css-m-36",
    "CSS",
    "Medium",
    "Grid",
    "What does `grid-template-areas` do?",
    "It lets you name grid regions and assign items to them by name, producing layouts that read visually in CSS. Combine with `grid-template-columns/rows` to set track sizes, and place children with `grid-area: name`.",
    ".layout { display: grid; grid-template-areas: 'nav main' 'nav foot'; grid-template-columns: 200px 1fr; }\n.nav { grid-area: nav; }",
  ),
  q(
    "css-m-37",
    "CSS",
    "Medium",
    "Flexbox",
    "What is the difference between `flex-basis` and `width` in a flex item?",
    "`flex-basis` is the flex item's initial main-size before free space is distributed by `flex-grow` and `flex-shrink`. It wins over `width` on the main axis. On the cross axis, `width`/`height` still apply.",
    ".item { flex: 1 1 200px; } /* grow shrink basis */",
  ),
  q(
    "css-m-38",
    "CSS",
    "Medium",
    "Transitions",
    "How do you transition only specific properties?",
    "List them individually in `transition-property` or use the shorthand with multiple entries separated by commas. Avoid `all` in production — it triggers unexpected reflows and hurts performance.",
    ".btn { transition: background 200ms ease, transform 150ms ease; }",
  ),
  q(
    "css-m-39",
    "CSS",
    "Medium",
    "Animations",
    "How do CSS `@keyframes` work?",
    "You define named keyframes with percentage checkpoints, then apply them with `animation`. The browser interpolates values between checkpoints. `0%` and `100%` (or `from`/`to`) mark the endpoints; you can add any number of intermediate steps.",
    "@keyframes bounce { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-8px); } }\n.dot { animation: bounce 1s infinite; }",
  ),
  q(
    "css-m-40",
    "CSS",
    "Medium",
    "Custom Properties",
    "What are CSS custom properties (variables)?",
    "They are user-defined properties prefixed with `--`, resolved at runtime and inherited. Read them with `var(--name, fallback)`. Unlike Sass variables, they respond to media queries, `:hover`, and can be updated from JavaScript.",
    ":root { --brand: #6366f1; }\n.btn { background: var(--brand); }",
  ),
  q(
    "css-m-41",
    "CSS",
    "Medium",
    "Selectors",
    "What does the `:is()` pseudo-class do?",
    "`:is(a, b, c)` matches any element that matches any selector in the list, but takes the highest specificity of the arguments. It shortens long selector lists without repeating combinators. `:where()` is the same but with zero specificity.",
    ":is(h1, h2, h3) a { color: inherit; }",
  ),
  q(
    "css-m-42",
    "CSS",
    "Medium",
    "Layout",
    "How do you make a card stretch to fill a grid track's full height?",
    "By default, grid items stretch on both axes unless you override `align-self`. If you have set `align-items: start`, restore the default with `align-self: stretch` on the item, or remove the parent override.",
    ".card { align-self: stretch; height: 100%; }",
  ),
  q(
    "css-m-43",
    "CSS",
    "Medium",
    "Media Queries",
    "How do you write a media query for prefers-reduced-motion?",
    "Use `@media (prefers-reduced-motion: reduce)` to disable or shorten animations for users who have that OS preference set. Respecting it is an accessibility requirement.",
    "@media (prefers-reduced-motion: reduce) { * { animation: none !important; transition: none !important; } }",
  ),
  q(
    "css-m-44",
    "CSS",
    "Medium",
    "Positioning",
    "When does `position: sticky` silently fail to stick?",
    "It fails if no `top`/`bottom` threshold is set, if any ancestor has `overflow: hidden`/`auto`/`scroll` (the sticky element sticks inside that ancestor, not the viewport), or if the container is shorter than the sticky element.",
    ".header { position: sticky; top: 0; }",
  ),
  q(
    "css-m-45",
    "CSS",
    "Medium",
    "Filters",
    "How do you blur only the background behind a card?",
    "Use `backdrop-filter: blur(...)` on the card itself, combined with a semi-transparent background. It blurs whatever is behind the element without affecting its own content. Safari requires `-webkit-backdrop-filter`.",
    ".glass { background: rgba(255,255,255,0.6); backdrop-filter: blur(12px); }",
  ),
  q(
    "css-a-21",
    "CSS",
    "Advanced",
    "Cascade Layers",
    "What are CSS `@layer` cascade layers?",
    "`@layer` groups rules into named layers with a defined order. Layers declared later beat earlier layers regardless of specificity, so you can slot vendor CSS below your overrides and keep specificity wars off the table.",
    "@layer reset, base, components, utilities;\n@layer components { .btn { color: white; } }",
  ),
  q(
    "css-a-22",
    "CSS",
    "Advanced",
    "Container Queries",
    "How do container queries differ from media queries?",
    "Media queries respond to viewport size; container queries respond to a parent's size. Mark the parent with `container-type: inline-size`, then write `@container (min-width: 400px) { … }`. Components become truly reusable across contexts.",
    ".card { container-type: inline-size; }\n@container (min-width: 400px) { .card h2 { font-size: 1.5rem; } }",
  ),
  q(
    "css-a-23",
    "CSS",
    "Advanced",
    "Subgrid",
    "What does `subgrid` solve?",
    "`grid-template-*: subgrid` lets a nested grid inherit its parent's tracks, so children of the child align to the outer grid's lines. It solves the long-standing problem of aligning items across sibling grid components.",
    ".list { display: grid; grid-template-columns: subgrid; grid-column: span 3; }",
  ),
  q(
    "css-a-24",
    "CSS",
    "Advanced",
    "Custom Properties",
    "How do you type a CSS custom property with `@property`?",
    "`@property` registers a custom property with a `syntax`, `inherits`, and `initial-value`. Typed properties can be animated smoothly (e.g. `<color>`), unlike plain variables which browsers treat as opaque strings.",
    "@property --tilt { syntax: '<angle>'; inherits: false; initial-value: 0deg; }",
  ),
  q(
    "css-a-25",
    "CSS",
    "Advanced",
    "Selectors",
    "What does `:has()` enable?",
    "`:has(selector)` is the parent selector — it matches an element that contains something matching the argument. It unlocks CSS patterns previously impossible without JS (e.g. `label:has(input:checked)` styles a label when its checkbox is on).",
    "label:has(input:checked) { color: green; }\n.card:has(img) { padding-top: 0; }",
  ),
  q(
    "css-a-26",
    "CSS",
    "Advanced",
    "Colors",
    "What does `color-mix()` do?",
    "It blends two colors in a given color space and ratio, e.g. `color-mix(in oklch, var(--brand) 80%, black)`. It removes the need to pre-compute tints/shades and works with custom properties.",
    ".btn:hover { background: color-mix(in oklch, var(--brand) 85%, black); }",
  ),
  q(
    "css-a-27",
    "CSS",
    "Advanced",
    "View Transitions",
    "What is the View Transitions API in CSS?",
    "Trigger a snapshot-to-snapshot cross-fade between DOM states with `document.startViewTransition(...)`. CSS pseudo-elements `::view-transition-*` let you customize the animation, including shared-element morphs via `view-transition-name`.",
    "document.startViewTransition(() => render());\n::view-transition-old(root) { animation: fade 200ms both; }",
  ),
  q(
    "css-a-28",
    "CSS",
    "Advanced",
    "Scroll",
    "What are CSS scroll-driven animations?",
    "`animation-timeline: scroll()` and `view()` let animations advance based on scroll position or an element's visibility within the viewport, without JavaScript. Great for scrollytelling and progress indicators.",
    "@keyframes fill { to { width: 100%; } }\n.bar { animation: fill linear; animation-timeline: scroll(root); }",
  ),
  q(
    "css-a-29",
    "CSS",
    "Advanced",
    "Logical Properties",
    "Why prefer `margin-inline` over `margin-left`/`margin-right`?",
    "Logical properties adapt to the writing mode and direction. `margin-inline-start` becomes right in RTL languages and top in vertical writing modes. This keeps components localized correctly with a single set of rules.",
    ".card { margin-inline: auto; padding-block: 24px; }",
  ),
  q(
    "css-a-30",
    "CSS",
    "Advanced",
    "Performance",
    "What is `contain` and when should you use it?",
    "`contain` tells the browser an element's subtree is independent — its layout, paint, or size does not affect the outside. Values include `layout`, `paint`, `size`, `style`, and `content`. It reduces work during reflow and enables optimizations like container queries.",
    ".widget { contain: layout paint; }",
  ),
  q(
    "css-a-31",
    "CSS",
    "Advanced",
    "Performance",
    "What is `content-visibility: auto`?",
    "It tells the browser to skip rendering work for offscreen elements until they scroll near the viewport, dramatically speeding up long pages. Provide `contain-intrinsic-size` so scroll position and page height stay stable.",
    ".section { content-visibility: auto; contain-intrinsic-size: 800px; }",
  ),
  q(
    "css-a-32",
    "CSS",
    "Advanced",
    "Rendering",
    "What triggers layout, paint, and composite?",
    "Changing geometry (width, top, margin) triggers layout → paint → composite. Changing appearance (color, background) triggers paint → composite. Compositor-only properties (`transform`, `opacity`, `filter` on GPU layers) trigger only composite and stay 60fps.",
    "/* Cheap */ .card { transform: translateX(10px); opacity: 0.8; }",
  ),
  q(
    "css-a-33",
    "CSS",
    "Advanced",
    "Animation",
    "Why animate `transform` instead of `top`/`left`?",
    "`transform` runs on the compositor thread and does not trigger layout or paint, so animations stay smooth. Animating `top`/`left` invalidates layout every frame and typically drops frames on complex pages.",
    ".card { transition: transform 200ms ease; }\n.card:hover { transform: translateY(-4px); }",
  ),
  q(
    "css-a-34",
    "CSS",
    "Advanced",
    "Shapes",
    "How does `clip-path` compare to `mask`?",
    "`clip-path` cuts geometry using a shape (`polygon()`, `circle()`, `path()`) — pixels outside are fully removed and don't receive events. `mask` uses an image whose alpha channel controls opacity, allowing soft, gradient-based cutouts.",
    ".badge { clip-path: polygon(0 0, 100% 0, 100% 80%, 50% 100%, 0 80%); }",
  ),
  q(
    "css-a-35",
    "CSS",
    "Advanced",
    "Anchor",
    "What is CSS Anchor Positioning?",
    "It positions an element relative to another named anchor, enabling tooltips, popovers, and menus without JavaScript positioning. Declare `anchor-name` on the anchor and `position-anchor` + `top/left: anchor(...)` on the positioned element.",
    ".btn { anchor-name: --menu; }\n.menu { position: absolute; top: anchor(--menu bottom); left: anchor(--menu left); }",
  ),
  q(
    "html-b-26",
    "HTML",
    "Basic",
    "Forms",
    "What does the `label` element do?",
    "It associates descriptive text with a form control. Clicking the label focuses the control and screen readers announce them together. Associate by wrapping the control or by pointing `for` at the control's `id`.",
    "<label for='email'>Email</label>\n<input id='email' type='email'>",
  ),
  q(
    "html-b-27",
    "HTML",
    "Basic",
    "Media",
    "How do you make an image responsive?",
    "Use `srcset` with multiple resolutions and `sizes` telling the browser how wide the image will render at each breakpoint. The browser picks the smallest sufficient source, saving bandwidth on small screens.",
    "<img src='hero-800.jpg' srcset='hero-400.jpg 400w, hero-800.jpg 800w, hero-1600.jpg 1600w' sizes='(max-width: 600px) 100vw, 800px' alt='...'>",
  ),
  q(
    "html-b-28",
    "HTML",
    "Basic",
    "Links",
    "What does `rel='noopener'` do on external links?",
    "It severs the link between the new tab and the page that opened it, so the target page cannot call `window.opener` to navigate or read the original page. Modern browsers add it automatically for `target='_blank'` but adding it explicitly is safer.",
    "<a href='https://example.com' target='_blank' rel='noopener noreferrer'>Docs</a>",
  ),
  q(
    "html-b-29",
    "HTML",
    "Basic",
    "Structure",
    "When should you use `article` vs `section`?",
    "Use `article` for content that stands on its own — a blog post, a comment, a product card that could be syndicated. Use `section` to group related content within a page that isn't independently distributable, ideally with a heading.",
    "<article><h2>Post title</h2><p>...</p></article>",
  ),
  q(
    "html-b-30",
    "HTML",
    "Basic",
    "Attributes",
    "What does the `title` attribute do and when should you avoid it?",
    "`title` shows a browser tooltip on hover. Avoid relying on it for critical info: it isn't shown on touch devices, has poor screen-reader support, and disappears quickly. Prefer visible text or accessible tooltips.",
    "<abbr title='HyperText Markup Language'>HTML</abbr>",
  ),
  q(
    "html-m-21",
    "HTML",
    "Medium",
    "Forms",
    "How do `autocomplete` tokens improve form UX?",
    "Tokens like `email`, `name`, `given-name`, `cc-number`, `one-time-code` help browsers and password managers fill fields correctly. They also enable OS-level autofill on mobile. Use `autocomplete='off'` sparingly — it often does nothing on credentials fields.",
    "<input name='email' type='email' autocomplete='email'>",
  ),
  q(
    "html-m-22",
    "HTML",
    "Medium",
    "Media",
    "What does the `picture` element do?",
    "It lets the browser choose from multiple `source` elements based on media queries or format support. Use it for art direction (different crops per breakpoint) or serving modern formats like AVIF/WebP with a JPEG fallback.",
    "<picture>\n  <source srcset='hero.avif' type='image/avif'>\n  <source srcset='hero.webp' type='image/webp'>\n  <img src='hero.jpg' alt='...'>\n</picture>",
  ),
  q(
    "html-m-23",
    "HTML",
    "Medium",
    "Accessibility",
    "What is an ARIA live region?",
    "An element with `aria-live='polite'` or `'assertive'` whose changes are announced by screen readers. Use it for toasts, form validation, and chat messages so users hear updates without needing focus.",
    "<div role='status' aria-live='polite'>Saved</div>",
  ),
  q(
    "html-m-24",
    "HTML",
    "Medium",
    "Accessibility",
    "What is the difference between `hidden`, `display: none`, and `aria-hidden`?",
    "`hidden` and `display: none` remove the element from layout AND from the accessibility tree. `aria-hidden='true'` hides only from assistive tech but still renders visually — use it for decorative icons alongside visible labels.",
    "<span aria-hidden='true'>*</span> Featured",
  ),
  q(
    "html-m-25",
    "HTML",
    "Medium",
    "Forms",
    "What is a `datalist`?",
    "A native autocomplete suggestions list associated with an `input` via `list=`. Users can pick a value or type freely. Lightweight for small option sets without shipping a JS combobox.",
    "<input list='colors'><datalist id='colors'><option>Red</option><option>Blue</option></datalist>",
  ),
  q(
    "html-m-26",
    "HTML",
    "Medium",
    "Media",
    "What does the `loading` attribute do?",
    "`loading='lazy'` on `<img>` and `<iframe>` defers loading until the element is near the viewport, saving bandwidth and speeding up first paint. Skip it for above-the-fold images — lazy loading them can slow LCP.",
    "<img src='...' loading='lazy' decoding='async' alt='...'>",
  ),
  q(
    "html-m-27",
    "HTML",
    "Medium",
    "Performance",
    "What is `<link rel='preload'>`?",
    "It tells the browser to fetch a critical resource (font, hero image, JS chunk) as early as possible. Include `as='...'` and `type='...'` so the browser can prioritize and validate it. Overusing preload harms performance.",
    "<link rel='preload' as='font' type='font/woff2' href='/fonts/inter.woff2' crossorigin>",
  ),
  q(
    "html-m-28",
    "HTML",
    "Medium",
    "Semantics",
    "What are `<details>` and `<summary>`?",
    "Native disclosure widget. `<details>` is the collapsible container and `<summary>` is the visible toggle. It's keyboard accessible and requires no JavaScript, ideal for FAQs and content-heavy help.",
    "<details><summary>Show more</summary><p>Hidden content...</p></details>",
  ),
  q(
    "html-m-29",
    "HTML",
    "Medium",
    "Semantics",
    "What does the `<dialog>` element provide?",
    "A native modal. `dialog.showModal()` opens it as a top layer with focus trapping, backdrop, and Escape-to-close. `dialog.show()` opens non-modally. Style the backdrop with `::backdrop`.",
    "<dialog id='m'><p>Are you sure?</p><form method='dialog'><button>OK</button></form></dialog>",
  ),
  q(
    "html-m-30",
    "HTML",
    "Medium",
    "Accessibility",
    "What is a skip link?",
    "A hidden-until-focused link at the top of the page that jumps to the main content, letting keyboard and screen-reader users bypass repetitive navigation. Required for good keyboard accessibility.",
    "<a class='skip' href='#main'>Skip to content</a>",
  ),
  q(
    "html-m-31",
    "HTML",
    "Medium",
    "Forms",
    "How do you group related radio buttons?",
    "Give them the same `name`. Only one can be selected at a time. Wrap the group in a `<fieldset>` with a `<legend>` so screen readers announce the group label.",
    "<fieldset><legend>Size</legend>\n<label><input type='radio' name='size' value='s'>S</label>\n<label><input type='radio' name='size' value='m'>M</label>\n</fieldset>",
  ),
  q(
    "html-m-32",
    "HTML",
    "Medium",
    "Meta",
    "What is Open Graph markup?",
    "A set of `<meta property='og:*'>` tags that control how a page appears when shared on Facebook, LinkedIn, iMessage, etc. Key ones are `og:title`, `og:description`, `og:image`, and `og:url`. Twitter has parallel `twitter:*` tags.",
    "<meta property='og:title' content='Page title'>\n<meta property='og:image' content='https://.../cover.png'>",
  ),
  q(
    "html-m-33",
    "HTML",
    "Medium",
    "Semantics",
    "What is the `<template>` element?",
    "An inert container whose children are parsed but not rendered until you clone them into the DOM. Perfect for JS-driven UIs — you write markup once in HTML and instantiate it as many times as needed.",
    "<template id='row'><tr><td></td></tr></template>",
  ),
  q(
    "html-a-13",
    "HTML",
    "Advanced",
    "Web Components",
    "What are Custom Elements?",
    "Browser-native components defined by extending `HTMLElement` and registered with `customElements.define('my-el', MyEl)`. They give you encapsulated tags with their own lifecycle callbacks, portable across frameworks.",
    "class MyBtn extends HTMLElement { connectedCallback(){ this.textContent = 'Hi'; } }\ncustomElements.define('my-btn', MyBtn);",
  ),
  q(
    "html-a-14",
    "HTML",
    "Advanced",
    "Web Components",
    "What is Shadow DOM?",
    "An encapsulated DOM tree attached to an element. Styles and IDs inside the shadow tree don't leak in or out, so components stay self-contained. `slot`s let consumers project light-DOM content into named holes.",
    "el.attachShadow({ mode: 'open' }).innerHTML = '<style>p{color:red}</style><p><slot></slot></p>';",
  ),
  q(
    "html-a-15",
    "HTML",
    "Advanced",
    "Accessibility",
    "How do you build an accessible custom combobox?",
    "Use `role='combobox'` on the input, `aria-expanded`, `aria-controls` pointing at the listbox, `aria-activedescendant` for the highlighted option, and manage keyboard events (Down/Up, Enter, Escape) manually. WAI-ARIA APG has the canonical pattern.",
    "<div role='combobox' aria-expanded='true' aria-controls='lb'>...</div>\n<ul id='lb' role='listbox'>...</ul>",
  ),
  q(
    "html-a-16",
    "HTML",
    "Advanced",
    "Security",
    "What is a strict Content Security Policy?",
    "A CSP header that whitelists exact sources for scripts, styles, images, and other resources. A good starting point uses nonces or hashes for inline scripts and disallows `unsafe-inline`/`unsafe-eval`, mitigating XSS by making injected script sources fail to load.",
    "Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-abc' 'strict-dynamic';",
  ),
  q(
    "html-a-17",
    "HTML",
    "Advanced",
    "Performance",
    "What are `preconnect`, `dns-prefetch`, and `prefetch`?",
    "`dns-prefetch` resolves DNS for a hostname you'll hit soon; `preconnect` also opens the TCP + TLS connection; `prefetch` downloads a resource likely needed on the next page and stores it in the cache. Use each for its intended stage — misusing hurts perf.",
    "<link rel='preconnect' href='https://api.example.com'>\n<link rel='prefetch' href='/next-page.js'>",
  ),
  q(
    "html-a-18",
    "HTML",
    "Advanced",
    "Streaming",
    "How does streaming HTML improve TTFB?",
    "Send the HTML as it's generated instead of buffering the whole response. The browser can start parsing, discover subresources via the preload scanner, and paint the shell before the server finishes. Frameworks like React Server Components rely on this.",
    "res.write('<head>...</head><body>');\nawait renderShell(res); res.write('...rest...');",
  ),
  q(
    "html-a-19",
    "HTML",
    "Advanced",
    "Meta",
    "What is JSON-LD structured data?",
    "A `<script type='application/ld+json'>` block containing schema.org data (Article, Product, FAQ, BreadcrumbList, etc.). Search engines use it for rich results. Keep it in sync with the visible content — mismatches can trigger manual actions.",
    '<script type=\'application/ld+json\'>{"@context":"https://schema.org","@type":"Article"}</script>',
  ),
  q(
    "html-a-20",
    "HTML",
    "Advanced",
    "APIs",
    "What is the IntersectionObserver API?",
    "A browser API for efficiently observing when elements enter or leave the viewport (or a scroll ancestor). It's the modern replacement for scroll-listener hacks used in lazy loading, infinite scroll, and reveal-on-scroll animations.",
    "new IntersectionObserver(entries => entries.forEach(e => e.isIntersecting && load(e.target))).observe(el);",
  ),
  q(
    "html-a-21",
    "HTML",
    "Advanced",
    "APIs",
    "What is a Service Worker?",
    "A script the browser runs in the background, independent of the page, that can intercept network requests. It powers offline support, custom caching strategies, background sync, and push notifications. Requires HTTPS.",
    "navigator.serviceWorker.register('/sw.js');",
  ),
  q(
    "html-a-22",
    "HTML",
    "Advanced",
    "Security",
    "What are Trusted Types?",
    "A browser feature that requires strings passed to XSS-prone sinks (`innerHTML`, `script.src`, ...) to be produced by a policy you define. It turns entire classes of DOM XSS from silent bugs into loud runtime errors during development.",
    "const p = trustedTypes.createPolicy('esc', { createHTML: s => sanitize(s) });\nel.innerHTML = p.createHTML(input);",
  ),
];

export const QUESTION_TOPICS = Array.from(new Set(INTERVIEW_QUESTIONS.map((q) => q.topic))).sort();
