import { createFileRoute } from "@tanstack/react-router";
import { ToolHeader } from "@/components/tool-header";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — SagaCSS" },
      {
        name: "description",
        content:
          "Terms of Service for SagaCSS — free, local-first CSS tools provided as-is with no warranty.",
      },
      { property: "og:title", content: "Terms of Service — SagaCSS" },
      {
        property: "og:description",
        content: "The simple terms that cover using SagaCSS's free CSS tools.",
      },
      { property: "og:url", content: "/terms" },
    ],
    links: [{ rel: "canonical", href: "/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-6">
      <ToolHeader
        title="Terms of Service"
        description="Plain-language terms — SagaCSS is free to use for everyone."
      />
      <div className="rounded-xl border border-border bg-card p-6 text-sm leading-7 text-foreground">
        <p>
          This page is maintained by the app owner to describe the basic terms of using SagaCSS. By
          using the app you agree to the points below.
        </p>

        <h2 className="mt-6 text-base font-semibold">1. Free &amp; as-is</h2>
        <p className="mt-2 text-muted-foreground">
          SagaCSS is provided free of charge, without warranty of any kind, express or implied. The
          tools are offered on an &quot;as-is&quot; and &quot;as-available&quot; basis. We do not
          guarantee that the app will be uninterrupted, error-free, or fit for any particular
          purpose.
        </p>

        <h2 className="mt-6 text-base font-semibold">2. Your content stays on your device</h2>
        <p className="mt-2 text-muted-foreground">
          Anything you design, save to My Kit, or configure is stored in your browser&apos;s
          localStorage on your own device. It is never uploaded to a server. Clearing your browser
          data will remove it — please export anything important.
        </p>

        <h2 className="mt-6 text-base font-semibold">3. Acceptable use</h2>
        <p className="mt-2 text-muted-foreground">
          Please use SagaCSS lawfully and don&apos;t attempt to disrupt the service for other users,
          reverse-engineer non-public parts, or misuse the tools to build content that violates the
          rights of others.
        </p>

        <h2 className="mt-6 text-base font-semibold">4. Generated snippets</h2>
        <p className="mt-2 text-muted-foreground">
          CSS, HTML, and configuration snippets generated by SagaCSS are free for you to use in
          personal or commercial projects. No attribution is required, though it&apos;s always
          appreciated.
        </p>

        <h2 className="mt-6 text-base font-semibold">5. Limitation of liability</h2>
        <p className="mt-2 text-muted-foreground">
          To the fullest extent permitted by law, the app owner is not liable for any indirect,
          incidental, or consequential damages arising from your use of SagaCSS.
        </p>

        <h2 className="mt-6 text-base font-semibold">6. Changes</h2>
        <p className="mt-2 text-muted-foreground">
          These terms may change over time as the app evolves. Continued use of SagaCSS after
          changes means you accept the updated terms.
        </p>

        <p className="mt-6 text-xs text-muted-foreground">
          This is app-owner editable content and is not legal advice. If you have a specific
          question, please reach out via the Contact page.
        </p>
      </div>
    </div>
  );
}
