/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MyKitRouteImport } from './routes/my-kit'
import { Route as InterviewPrepRouteImport } from './routes/interview-prep'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheatSheetRouteImport } from './routes/cheat-sheet'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsThemeVariablesRouteImport } from './routes/tools/theme-variables'
import { Route as ToolsThemeRouteImport } from './routes/tools/theme'
import { Route as ToolsTextShadowRouteImport } from './routes/tools/text-shadow'
import { Route as ToolsSvgRouteImport } from './routes/tools/svg'
import { Route as ToolsSpinnerRouteImport } from './routes/tools/spinner'
import { Route as ToolsSpecificityRouteImport } from './routes/tools/specificity'
import { Route as ToolsScrollbarRouteImport } from './routes/tools/scrollbar'
import { Route as ToolsResponsiveRouteImport } from './routes/tools/responsive'
import { Route as ToolsResetRouteImport } from './routes/tools/reset'
import { Route as ToolsPreprocessorRouteImport } from './routes/tools/preprocessor'
import { Route as ToolsImageTextRouteImport } from './routes/tools/image-text'
import { Route as ToolsGridRouteImport } from './routes/tools/grid'
import { Route as ToolsGradientRouteImport } from './routes/tools/gradient'
import { Route as ToolsFontsRouteImport } from './routes/tools/fonts'
import { Route as ToolsFlexboxRouteImport } from './routes/tools/flexbox'
import { Route as ToolsFilterRouteImport } from './routes/tools/filter'
import { Route as ToolsContrastRouteImport } from './routes/tools/contrast'
import { Route as ToolsCompatibilityRouteImport } from './routes/tools/compatibility'
import { Route as ToolsColorPaletteRouteImport } from './routes/tools/color-palette'
import { Route as ToolsColorMixerRouteImport } from './routes/tools/color-mixer'
import { Route as ToolsColorConverterRouteImport } from './routes/tools/color-converter'
import { Route as ToolsClipPathRouteImport } from './routes/tools/clip-path'
import { Route as ToolsClampRouteImport } from './routes/tools/clamp'
import { Route as ToolsButtonRouteImport } from './routes/tools/button'
import { Route as ToolsBoxSizingRouteImport } from './routes/tools/box-sizing'
import { Route as ToolsBoxShadowRouteImport } from './routes/tools/box-shadow'
import { Route as ToolsBorderRadiusRouteImport } from './routes/tools/border-radius'
import { Route as ToolsBezierRouteImport } from './routes/tools/bezier'
import { Route as ToolsBase64RouteImport } from './routes/tools/base64'
import { Route as ToolsAnimationRouteImport } from './routes/tools/animation'
import { Route as Tools3dShapesRouteImport } from './routes/tools/3d-shapes'
import { Route as StylesY2kRouteImport } from './routes/styles/y2k'
import { Route as StylesNeumorphismRouteImport } from './routes/styles/neumorphism'
import { Route as StylesNeubrutalismRouteImport } from './routes/styles/neubrutalism'
import { Route as StylesGlassmorphismRouteImport } from './routes/styles/glassmorphism'
import { Route as StylesCyberpunkRouteImport } from './routes/styles/cyberpunk'
import { Route as StylesClaymorphismRouteImport } from './routes/styles/claymorphism'
import { Route as StylesArtDecoRouteImport } from './routes/styles/art-deco'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogPagePageRouteImport } from './routes/blog.page.$page'
import { Route as ApiPublicVitalsRouteImport } from './routes/api/public/vitals'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MyKitRoute = MyKitRouteImport.update({
  id: '/my-kit',
  path: '/my-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewPrepRoute = InterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatSheetRoute = CheatSheetRouteImport.update({
  id: '/cheat-sheet',
  path: '/cheat-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsThemeVariablesRoute = ToolsThemeVariablesRouteImport.update({
  id: '/tools/theme-variables',
  path: '/tools/theme-variables',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsThemeRoute = ToolsThemeRouteImport.update({
  id: '/tools/theme',
  path: '/tools/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTextShadowRoute = ToolsTextShadowRouteImport.update({
  id: '/tools/text-shadow',
  path: '/tools/text-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSvgRoute = ToolsSvgRouteImport.update({
  id: '/tools/svg',
  path: '/tools/svg',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSpinnerRoute = ToolsSpinnerRouteImport.update({
  id: '/tools/spinner',
  path: '/tools/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSpecificityRoute = ToolsSpecificityRouteImport.update({
  id: '/tools/specificity',
  path: '/tools/specificity',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsScrollbarRoute = ToolsScrollbarRouteImport.update({
  id: '/tools/scrollbar',
  path: '/tools/scrollbar',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsResponsiveRoute = ToolsResponsiveRouteImport.update({
  id: '/tools/responsive',
  path: '/tools/responsive',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsResetRoute = ToolsResetRouteImport.update({
  id: '/tools/reset',
  path: '/tools/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPreprocessorRoute = ToolsPreprocessorRouteImport.update({
  id: '/tools/preprocessor',
  path: '/tools/preprocessor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageTextRoute = ToolsImageTextRouteImport.update({
  id: '/tools/image-text',
  path: '/tools/image-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGridRoute = ToolsGridRouteImport.update({
  id: '/tools/grid',
  path: '/tools/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGradientRoute = ToolsGradientRouteImport.update({
  id: '/tools/gradient',
  path: '/tools/gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFontsRoute = ToolsFontsRouteImport.update({
  id: '/tools/fonts',
  path: '/tools/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFlexboxRoute = ToolsFlexboxRouteImport.update({
  id: '/tools/flexbox',
  path: '/tools/flexbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFilterRoute = ToolsFilterRouteImport.update({
  id: '/tools/filter',
  path: '/tools/filter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsContrastRoute = ToolsContrastRouteImport.update({
  id: '/tools/contrast',
  path: '/tools/contrast',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompatibilityRoute = ToolsCompatibilityRouteImport.update({
  id: '/tools/compatibility',
  path: '/tools/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorPaletteRoute = ToolsColorPaletteRouteImport.update({
  id: '/tools/color-palette',
  path: '/tools/color-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorMixerRoute = ToolsColorMixerRouteImport.update({
  id: '/tools/color-mixer',
  path: '/tools/color-mixer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorConverterRoute = ToolsColorConverterRouteImport.update({
  id: '/tools/color-converter',
  path: '/tools/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsClipPathRoute = ToolsClipPathRouteImport.update({
  id: '/tools/clip-path',
  path: '/tools/clip-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsClampRoute = ToolsClampRouteImport.update({
  id: '/tools/clamp',
  path: '/tools/clamp',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsButtonRoute = ToolsButtonRouteImport.update({
  id: '/tools/button',
  path: '/tools/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBoxSizingRoute = ToolsBoxSizingRouteImport.update({
  id: '/tools/box-sizing',
  path: '/tools/box-sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBoxShadowRoute = ToolsBoxShadowRouteImport.update({
  id: '/tools/box-shadow',
  path: '/tools/box-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBorderRadiusRoute = ToolsBorderRadiusRouteImport.update({
  id: '/tools/border-radius',
  path: '/tools/border-radius',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBezierRoute = ToolsBezierRouteImport.update({
  id: '/tools/bezier',
  path: '/tools/bezier',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/tools/base64',
  path: '/tools/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAnimationRoute = ToolsAnimationRouteImport.update({
  id: '/tools/animation',
  path: '/tools/animation',
  getParentRoute: () => rootRouteImport,
} as any)
const Tools3dShapesRoute = Tools3dShapesRouteImport.update({
  id: '/tools/3d-shapes',
  path: '/tools/3d-shapes',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesY2kRoute = StylesY2kRouteImport.update({
  id: '/styles/y2k',
  path: '/styles/y2k',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesNeumorphismRoute = StylesNeumorphismRouteImport.update({
  id: '/styles/neumorphism',
  path: '/styles/neumorphism',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesNeubrutalismRoute = StylesNeubrutalismRouteImport.update({
  id: '/styles/neubrutalism',
  path: '/styles/neubrutalism',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesGlassmorphismRoute = StylesGlassmorphismRouteImport.update({
  id: '/styles/glassmorphism',
  path: '/styles/glassmorphism',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesCyberpunkRoute = StylesCyberpunkRouteImport.update({
  id: '/styles/cyberpunk',
  path: '/styles/cyberpunk',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesClaymorphismRoute = StylesClaymorphismRouteImport.update({
  id: '/styles/claymorphism',
  path: '/styles/claymorphism',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesArtDecoRoute = StylesArtDecoRouteImport.update({
  id: '/styles/art-deco',
  path: '/styles/art-deco',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPagePageRoute = BlogPagePageRouteImport.update({
  id: '/blog/page/$page',
  path: '/blog/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVitalsRoute = ApiPublicVitalsRouteImport.update({
  id: '/api/public/vitals',
  path: '/api/public/vitals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/my-kit': typeof MyKitRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/styles/art-deco': typeof StylesArtDecoRoute
  '/styles/claymorphism': typeof StylesClaymorphismRoute
  '/styles/cyberpunk': typeof StylesCyberpunkRoute
  '/styles/glassmorphism': typeof StylesGlassmorphismRoute
  '/styles/neubrutalism': typeof StylesNeubrutalismRoute
  '/styles/neumorphism': typeof StylesNeumorphismRoute
  '/styles/y2k': typeof StylesY2kRoute
  '/tools/3d-shapes': typeof Tools3dShapesRoute
  '/tools/animation': typeof ToolsAnimationRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/bezier': typeof ToolsBezierRoute
  '/tools/border-radius': typeof ToolsBorderRadiusRoute
  '/tools/box-shadow': typeof ToolsBoxShadowRoute
  '/tools/box-sizing': typeof ToolsBoxSizingRoute
  '/tools/button': typeof ToolsButtonRoute
  '/tools/clamp': typeof ToolsClampRoute
  '/tools/clip-path': typeof ToolsClipPathRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/color-mixer': typeof ToolsColorMixerRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/compatibility': typeof ToolsCompatibilityRoute
  '/tools/contrast': typeof ToolsContrastRoute
  '/tools/filter': typeof ToolsFilterRoute
  '/tools/flexbox': typeof ToolsFlexboxRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/grid': typeof ToolsGridRoute
  '/tools/image-text': typeof ToolsImageTextRoute
  '/tools/preprocessor': typeof ToolsPreprocessorRoute
  '/tools/reset': typeof ToolsResetRoute
  '/tools/responsive': typeof ToolsResponsiveRoute
  '/tools/scrollbar': typeof ToolsScrollbarRoute
  '/tools/specificity': typeof ToolsSpecificityRoute
  '/tools/spinner': typeof ToolsSpinnerRoute
  '/tools/svg': typeof ToolsSvgRoute
  '/tools/text-shadow': typeof ToolsTextShadowRoute
  '/tools/theme': typeof ToolsThemeRoute
  '/tools/theme-variables': typeof ToolsThemeVariablesRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/my-kit': typeof MyKitRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/styles/art-deco': typeof StylesArtDecoRoute
  '/styles/claymorphism': typeof StylesClaymorphismRoute
  '/styles/cyberpunk': typeof StylesCyberpunkRoute
  '/styles/glassmorphism': typeof StylesGlassmorphismRoute
  '/styles/neubrutalism': typeof StylesNeubrutalismRoute
  '/styles/neumorphism': typeof StylesNeumorphismRoute
  '/styles/y2k': typeof StylesY2kRoute
  '/tools/3d-shapes': typeof Tools3dShapesRoute
  '/tools/animation': typeof ToolsAnimationRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/bezier': typeof ToolsBezierRoute
  '/tools/border-radius': typeof ToolsBorderRadiusRoute
  '/tools/box-shadow': typeof ToolsBoxShadowRoute
  '/tools/box-sizing': typeof ToolsBoxSizingRoute
  '/tools/button': typeof ToolsButtonRoute
  '/tools/clamp': typeof ToolsClampRoute
  '/tools/clip-path': typeof ToolsClipPathRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/color-mixer': typeof ToolsColorMixerRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/compatibility': typeof ToolsCompatibilityRoute
  '/tools/contrast': typeof ToolsContrastRoute
  '/tools/filter': typeof ToolsFilterRoute
  '/tools/flexbox': typeof ToolsFlexboxRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/grid': typeof ToolsGridRoute
  '/tools/image-text': typeof ToolsImageTextRoute
  '/tools/preprocessor': typeof ToolsPreprocessorRoute
  '/tools/reset': typeof ToolsResetRoute
  '/tools/responsive': typeof ToolsResponsiveRoute
  '/tools/scrollbar': typeof ToolsScrollbarRoute
  '/tools/specificity': typeof ToolsSpecificityRoute
  '/tools/spinner': typeof ToolsSpinnerRoute
  '/tools/svg': typeof ToolsSvgRoute
  '/tools/text-shadow': typeof ToolsTextShadowRoute
  '/tools/theme': typeof ToolsThemeRoute
  '/tools/theme-variables': typeof ToolsThemeVariablesRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/interview-prep': typeof InterviewPrepRoute
  '/my-kit': typeof MyKitRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/styles/art-deco': typeof StylesArtDecoRoute
  '/styles/claymorphism': typeof StylesClaymorphismRoute
  '/styles/cyberpunk': typeof StylesCyberpunkRoute
  '/styles/glassmorphism': typeof StylesGlassmorphismRoute
  '/styles/neubrutalism': typeof StylesNeubrutalismRoute
  '/styles/neumorphism': typeof StylesNeumorphismRoute
  '/styles/y2k': typeof StylesY2kRoute
  '/tools/3d-shapes': typeof Tools3dShapesRoute
  '/tools/animation': typeof ToolsAnimationRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/bezier': typeof ToolsBezierRoute
  '/tools/border-radius': typeof ToolsBorderRadiusRoute
  '/tools/box-shadow': typeof ToolsBoxShadowRoute
  '/tools/box-sizing': typeof ToolsBoxSizingRoute
  '/tools/button': typeof ToolsButtonRoute
  '/tools/clamp': typeof ToolsClampRoute
  '/tools/clip-path': typeof ToolsClipPathRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/color-mixer': typeof ToolsColorMixerRoute
  '/tools/color-palette': typeof ToolsColorPaletteRoute
  '/tools/compatibility': typeof ToolsCompatibilityRoute
  '/tools/contrast': typeof ToolsContrastRoute
  '/tools/filter': typeof ToolsFilterRoute
  '/tools/flexbox': typeof ToolsFlexboxRoute
  '/tools/fonts': typeof ToolsFontsRoute
  '/tools/gradient': typeof ToolsGradientRoute
  '/tools/grid': typeof ToolsGridRoute
  '/tools/image-text': typeof ToolsImageTextRoute
  '/tools/preprocessor': typeof ToolsPreprocessorRoute
  '/tools/reset': typeof ToolsResetRoute
  '/tools/responsive': typeof ToolsResponsiveRoute
  '/tools/scrollbar': typeof ToolsScrollbarRoute
  '/tools/specificity': typeof ToolsSpecificityRoute
  '/tools/spinner': typeof ToolsSpinnerRoute
  '/tools/svg': typeof ToolsSvgRoute
  '/tools/text-shadow': typeof ToolsTextShadowRoute
  '/tools/theme': typeof ToolsThemeRoute
  '/tools/theme-variables': typeof ToolsThemeVariablesRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cheat-sheet'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/interview-prep'
    | '/my-kit'
    | '/practice'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/styles/art-deco'
    | '/styles/claymorphism'
    | '/styles/cyberpunk'
    | '/styles/glassmorphism'
    | '/styles/neubrutalism'
    | '/styles/neumorphism'
    | '/styles/y2k'
    | '/tools/3d-shapes'
    | '/tools/animation'
    | '/tools/base64'
    | '/tools/bezier'
    | '/tools/border-radius'
    | '/tools/box-shadow'
    | '/tools/box-sizing'
    | '/tools/button'
    | '/tools/clamp'
    | '/tools/clip-path'
    | '/tools/color-converter'
    | '/tools/color-mixer'
    | '/tools/color-palette'
    | '/tools/compatibility'
    | '/tools/contrast'
    | '/tools/filter'
    | '/tools/flexbox'
    | '/tools/fonts'
    | '/tools/gradient'
    | '/tools/grid'
    | '/tools/image-text'
    | '/tools/preprocessor'
    | '/tools/reset'
    | '/tools/responsive'
    | '/tools/scrollbar'
    | '/tools/specificity'
    | '/tools/spinner'
    | '/tools/svg'
    | '/tools/text-shadow'
    | '/tools/theme'
    | '/tools/theme-variables'
    | '/blog/'
    | '/api/public/vitals'
    | '/blog/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cheat-sheet'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/interview-prep'
    | '/my-kit'
    | '/practice'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/styles/art-deco'
    | '/styles/claymorphism'
    | '/styles/cyberpunk'
    | '/styles/glassmorphism'
    | '/styles/neubrutalism'
    | '/styles/neumorphism'
    | '/styles/y2k'
    | '/tools/3d-shapes'
    | '/tools/animation'
    | '/tools/base64'
    | '/tools/bezier'
    | '/tools/border-radius'
    | '/tools/box-shadow'
    | '/tools/box-sizing'
    | '/tools/button'
    | '/tools/clamp'
    | '/tools/clip-path'
    | '/tools/color-converter'
    | '/tools/color-mixer'
    | '/tools/color-palette'
    | '/tools/compatibility'
    | '/tools/contrast'
    | '/tools/filter'
    | '/tools/flexbox'
    | '/tools/fonts'
    | '/tools/gradient'
    | '/tools/grid'
    | '/tools/image-text'
    | '/tools/preprocessor'
    | '/tools/reset'
    | '/tools/responsive'
    | '/tools/scrollbar'
    | '/tools/specificity'
    | '/tools/spinner'
    | '/tools/svg'
    | '/tools/text-shadow'
    | '/tools/theme'
    | '/tools/theme-variables'
    | '/blog'
    | '/api/public/vitals'
    | '/blog/page/$page'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cheat-sheet'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/interview-prep'
    | '/my-kit'
    | '/practice'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/styles/art-deco'
    | '/styles/claymorphism'
    | '/styles/cyberpunk'
    | '/styles/glassmorphism'
    | '/styles/neubrutalism'
    | '/styles/neumorphism'
    | '/styles/y2k'
    | '/tools/3d-shapes'
    | '/tools/animation'
    | '/tools/base64'
    | '/tools/bezier'
    | '/tools/border-radius'
    | '/tools/box-shadow'
    | '/tools/box-sizing'
    | '/tools/button'
    | '/tools/clamp'
    | '/tools/clip-path'
    | '/tools/color-converter'
    | '/tools/color-mixer'
    | '/tools/color-palette'
    | '/tools/compatibility'
    | '/tools/contrast'
    | '/tools/filter'
    | '/tools/flexbox'
    | '/tools/fonts'
    | '/tools/gradient'
    | '/tools/grid'
    | '/tools/image-text'
    | '/tools/preprocessor'
    | '/tools/reset'
    | '/tools/responsive'
    | '/tools/scrollbar'
    | '/tools/specificity'
    | '/tools/spinner'
    | '/tools/svg'
    | '/tools/text-shadow'
    | '/tools/theme'
    | '/tools/theme-variables'
    | '/blog/'
    | '/api/public/vitals'
    | '/blog/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheatSheetRoute: typeof CheatSheetRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  InterviewPrepRoute: typeof InterviewPrepRoute
  MyKitRoute: typeof MyKitRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  StylesArtDecoRoute: typeof StylesArtDecoRoute
  StylesClaymorphismRoute: typeof StylesClaymorphismRoute
  StylesCyberpunkRoute: typeof StylesCyberpunkRoute
  StylesGlassmorphismRoute: typeof StylesGlassmorphismRoute
  StylesNeubrutalismRoute: typeof StylesNeubrutalismRoute
  StylesNeumorphismRoute: typeof StylesNeumorphismRoute
  StylesY2kRoute: typeof StylesY2kRoute
  Tools3dShapesRoute: typeof Tools3dShapesRoute
  ToolsAnimationRoute: typeof ToolsAnimationRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsBezierRoute: typeof ToolsBezierRoute
  ToolsBorderRadiusRoute: typeof ToolsBorderRadiusRoute
  ToolsBoxShadowRoute: typeof ToolsBoxShadowRoute
  ToolsBoxSizingRoute: typeof ToolsBoxSizingRoute
  ToolsButtonRoute: typeof ToolsButtonRoute
  ToolsClampRoute: typeof ToolsClampRoute
  ToolsClipPathRoute: typeof ToolsClipPathRoute
  ToolsColorConverterRoute: typeof ToolsColorConverterRoute
  ToolsColorMixerRoute: typeof ToolsColorMixerRoute
  ToolsColorPaletteRoute: typeof ToolsColorPaletteRoute
  ToolsCompatibilityRoute: typeof ToolsCompatibilityRoute
  ToolsContrastRoute: typeof ToolsContrastRoute
  ToolsFilterRoute: typeof ToolsFilterRoute
  ToolsFlexboxRoute: typeof ToolsFlexboxRoute
  ToolsFontsRoute: typeof ToolsFontsRoute
  ToolsGradientRoute: typeof ToolsGradientRoute
  ToolsGridRoute: typeof ToolsGridRoute
  ToolsImageTextRoute: typeof ToolsImageTextRoute
  ToolsPreprocessorRoute: typeof ToolsPreprocessorRoute
  ToolsResetRoute: typeof ToolsResetRoute
  ToolsResponsiveRoute: typeof ToolsResponsiveRoute
  ToolsScrollbarRoute: typeof ToolsScrollbarRoute
  ToolsSpecificityRoute: typeof ToolsSpecificityRoute
  ToolsSpinnerRoute: typeof ToolsSpinnerRoute
  ToolsSvgRoute: typeof ToolsSvgRoute
  ToolsTextShadowRoute: typeof ToolsTextShadowRoute
  ToolsThemeRoute: typeof ToolsThemeRoute
  ToolsThemeVariablesRoute: typeof ToolsThemeVariablesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicVitalsRoute: typeof ApiPublicVitalsRoute
  BlogPagePageRoute: typeof BlogPagePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-kit': {
      id: '/my-kit'
      path: '/my-kit'
      fullPath: '/my-kit'
      preLoaderRoute: typeof MyKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-prep': {
      id: '/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof InterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheat-sheet': {
      id: '/cheat-sheet'
      path: '/cheat-sheet'
      fullPath: '/cheat-sheet'
      preLoaderRoute: typeof CheatSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/theme-variables': {
      id: '/tools/theme-variables'
      path: '/tools/theme-variables'
      fullPath: '/tools/theme-variables'
      preLoaderRoute: typeof ToolsThemeVariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/theme': {
      id: '/tools/theme'
      path: '/tools/theme'
      fullPath: '/tools/theme'
      preLoaderRoute: typeof ToolsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/text-shadow': {
      id: '/tools/text-shadow'
      path: '/tools/text-shadow'
      fullPath: '/tools/text-shadow'
      preLoaderRoute: typeof ToolsTextShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/svg': {
      id: '/tools/svg'
      path: '/tools/svg'
      fullPath: '/tools/svg'
      preLoaderRoute: typeof ToolsSvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/spinner': {
      id: '/tools/spinner'
      path: '/tools/spinner'
      fullPath: '/tools/spinner'
      preLoaderRoute: typeof ToolsSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/specificity': {
      id: '/tools/specificity'
      path: '/tools/specificity'
      fullPath: '/tools/specificity'
      preLoaderRoute: typeof ToolsSpecificityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/scrollbar': {
      id: '/tools/scrollbar'
      path: '/tools/scrollbar'
      fullPath: '/tools/scrollbar'
      preLoaderRoute: typeof ToolsScrollbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/responsive': {
      id: '/tools/responsive'
      path: '/tools/responsive'
      fullPath: '/tools/responsive'
      preLoaderRoute: typeof ToolsResponsiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/reset': {
      id: '/tools/reset'
      path: '/tools/reset'
      fullPath: '/tools/reset'
      preLoaderRoute: typeof ToolsResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/preprocessor': {
      id: '/tools/preprocessor'
      path: '/tools/preprocessor'
      fullPath: '/tools/preprocessor'
      preLoaderRoute: typeof ToolsPreprocessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-text': {
      id: '/tools/image-text'
      path: '/tools/image-text'
      fullPath: '/tools/image-text'
      preLoaderRoute: typeof ToolsImageTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/grid': {
      id: '/tools/grid'
      path: '/tools/grid'
      fullPath: '/tools/grid'
      preLoaderRoute: typeof ToolsGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/gradient': {
      id: '/tools/gradient'
      path: '/tools/gradient'
      fullPath: '/tools/gradient'
      preLoaderRoute: typeof ToolsGradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/fonts': {
      id: '/tools/fonts'
      path: '/tools/fonts'
      fullPath: '/tools/fonts'
      preLoaderRoute: typeof ToolsFontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/flexbox': {
      id: '/tools/flexbox'
      path: '/tools/flexbox'
      fullPath: '/tools/flexbox'
      preLoaderRoute: typeof ToolsFlexboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/filter': {
      id: '/tools/filter'
      path: '/tools/filter'
      fullPath: '/tools/filter'
      preLoaderRoute: typeof ToolsFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/contrast': {
      id: '/tools/contrast'
      path: '/tools/contrast'
      fullPath: '/tools/contrast'
      preLoaderRoute: typeof ToolsContrastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compatibility': {
      id: '/tools/compatibility'
      path: '/tools/compatibility'
      fullPath: '/tools/compatibility'
      preLoaderRoute: typeof ToolsCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-palette': {
      id: '/tools/color-palette'
      path: '/tools/color-palette'
      fullPath: '/tools/color-palette'
      preLoaderRoute: typeof ToolsColorPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-mixer': {
      id: '/tools/color-mixer'
      path: '/tools/color-mixer'
      fullPath: '/tools/color-mixer'
      preLoaderRoute: typeof ToolsColorMixerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-converter': {
      id: '/tools/color-converter'
      path: '/tools/color-converter'
      fullPath: '/tools/color-converter'
      preLoaderRoute: typeof ToolsColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/clip-path': {
      id: '/tools/clip-path'
      path: '/tools/clip-path'
      fullPath: '/tools/clip-path'
      preLoaderRoute: typeof ToolsClipPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/clamp': {
      id: '/tools/clamp'
      path: '/tools/clamp'
      fullPath: '/tools/clamp'
      preLoaderRoute: typeof ToolsClampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/button': {
      id: '/tools/button'
      path: '/tools/button'
      fullPath: '/tools/button'
      preLoaderRoute: typeof ToolsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/box-sizing': {
      id: '/tools/box-sizing'
      path: '/tools/box-sizing'
      fullPath: '/tools/box-sizing'
      preLoaderRoute: typeof ToolsBoxSizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/box-shadow': {
      id: '/tools/box-shadow'
      path: '/tools/box-shadow'
      fullPath: '/tools/box-shadow'
      preLoaderRoute: typeof ToolsBoxShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/border-radius': {
      id: '/tools/border-radius'
      path: '/tools/border-radius'
      fullPath: '/tools/border-radius'
      preLoaderRoute: typeof ToolsBorderRadiusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bezier': {
      id: '/tools/bezier'
      path: '/tools/bezier'
      fullPath: '/tools/bezier'
      preLoaderRoute: typeof ToolsBezierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/tools/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/animation': {
      id: '/tools/animation'
      path: '/tools/animation'
      fullPath: '/tools/animation'
      preLoaderRoute: typeof ToolsAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/3d-shapes': {
      id: '/tools/3d-shapes'
      path: '/tools/3d-shapes'
      fullPath: '/tools/3d-shapes'
      preLoaderRoute: typeof Tools3dShapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/y2k': {
      id: '/styles/y2k'
      path: '/styles/y2k'
      fullPath: '/styles/y2k'
      preLoaderRoute: typeof StylesY2kRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/neumorphism': {
      id: '/styles/neumorphism'
      path: '/styles/neumorphism'
      fullPath: '/styles/neumorphism'
      preLoaderRoute: typeof StylesNeumorphismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/neubrutalism': {
      id: '/styles/neubrutalism'
      path: '/styles/neubrutalism'
      fullPath: '/styles/neubrutalism'
      preLoaderRoute: typeof StylesNeubrutalismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/glassmorphism': {
      id: '/styles/glassmorphism'
      path: '/styles/glassmorphism'
      fullPath: '/styles/glassmorphism'
      preLoaderRoute: typeof StylesGlassmorphismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/cyberpunk': {
      id: '/styles/cyberpunk'
      path: '/styles/cyberpunk'
      fullPath: '/styles/cyberpunk'
      preLoaderRoute: typeof StylesCyberpunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/claymorphism': {
      id: '/styles/claymorphism'
      path: '/styles/claymorphism'
      fullPath: '/styles/claymorphism'
      preLoaderRoute: typeof StylesClaymorphismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/art-deco': {
      id: '/styles/art-deco'
      path: '/styles/art-deco'
      fullPath: '/styles/art-deco'
      preLoaderRoute: typeof StylesArtDecoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/page/$page': {
      id: '/blog/page/$page'
      path: '/blog/page/$page'
      fullPath: '/blog/page/$page'
      preLoaderRoute: typeof BlogPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vitals': {
      id: '/api/public/vitals'
      path: '/api/public/vitals'
      fullPath: '/api/public/vitals'
      preLoaderRoute: typeof ApiPublicVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheatSheetRoute: CheatSheetRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  InterviewPrepRoute: InterviewPrepRoute,
  MyKitRoute: MyKitRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  StylesArtDecoRoute: StylesArtDecoRoute,
  StylesClaymorphismRoute: StylesClaymorphismRoute,
  StylesCyberpunkRoute: StylesCyberpunkRoute,
  StylesGlassmorphismRoute: StylesGlassmorphismRoute,
  StylesNeubrutalismRoute: StylesNeubrutalismRoute,
  StylesNeumorphismRoute: StylesNeumorphismRoute,
  StylesY2kRoute: StylesY2kRoute,
  Tools3dShapesRoute: Tools3dShapesRoute,
  ToolsAnimationRoute: ToolsAnimationRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsBezierRoute: ToolsBezierRoute,
  ToolsBorderRadiusRoute: ToolsBorderRadiusRoute,
  ToolsBoxShadowRoute: ToolsBoxShadowRoute,
  ToolsBoxSizingRoute: ToolsBoxSizingRoute,
  ToolsButtonRoute: ToolsButtonRoute,
  ToolsClampRoute: ToolsClampRoute,
  ToolsClipPathRoute: ToolsClipPathRoute,
  ToolsColorConverterRoute: ToolsColorConverterRoute,
  ToolsColorMixerRoute: ToolsColorMixerRoute,
  ToolsColorPaletteRoute: ToolsColorPaletteRoute,
  ToolsCompatibilityRoute: ToolsCompatibilityRoute,
  ToolsContrastRoute: ToolsContrastRoute,
  ToolsFilterRoute: ToolsFilterRoute,
  ToolsFlexboxRoute: ToolsFlexboxRoute,
  ToolsFontsRoute: ToolsFontsRoute,
  ToolsGradientRoute: ToolsGradientRoute,
  ToolsGridRoute: ToolsGridRoute,
  ToolsImageTextRoute: ToolsImageTextRoute,
  ToolsPreprocessorRoute: ToolsPreprocessorRoute,
  ToolsResetRoute: ToolsResetRoute,
  ToolsResponsiveRoute: ToolsResponsiveRoute,
  ToolsScrollbarRoute: ToolsScrollbarRoute,
  ToolsSpecificityRoute: ToolsSpecificityRoute,
  ToolsSpinnerRoute: ToolsSpinnerRoute,
  ToolsSvgRoute: ToolsSvgRoute,
  ToolsTextShadowRoute: ToolsTextShadowRoute,
  ToolsThemeRoute: ToolsThemeRoute,
  ToolsThemeVariablesRoute: ToolsThemeVariablesRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicVitalsRoute: ApiPublicVitalsRoute,
  BlogPagePageRoute: BlogPagePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
